### ISSUE TITLE
Config file does not change anything

### ISSUE THREAD

**Issue by Hermeleginda** [P3pp3rF1y/SophisticatedStorage#10]
Core 0.1.0.19
Sophisticated Storage 0.0.10.22

Title explain the problem.
Tried both lowering upgrade slots number and increasing the storage slots - both does not have an effect in-game.

**Comment by P3pp3rF1y** [comment]
Have you crafted a new chest/barrel/shulker box after or at least break the chest / barrel and place it again? because it will not have any effect on already existing ones.

**Comment by Hermeleginda** [comment]
Yes, I tried making new ones

**Comment by P3pp3rF1y** [comment]
found the issue, will be fixed in the next release
