### ISSUE TITLE
RubidiumExtra Compatibility

### ISSUE THREAD

**Issue by Dr-WeiAL** [P3pp3rF1y/SophisticatedStorage#111]
Installing with RubidiumExtra will cause the barrel with color to display abnormally
![image](https://user-images.githubusercontent.com/47446553/206897109-ef4dbf14-ce99-4a35-8e5f-ed6df196a1e6.png)
![image](https://user-images.githubusercontent.com/47446553/206897138-7e38cf70-805b-4a0c-9164-9b171f7f582c.png)

**Comment by P3pp3rF1y** [comment]
You will need to report this to them as sophisticated just uses regular coloring of blocks that's supported by vanilla.

**Comment by P3pp3rF1y** [comment]
this seems to be the exact same issue that rubidium extras causes to another mod https://github.com/TeamDeusVult/MagnesiumExtras/issues/34

**Comment by Dr-WeiAL** [comment]
Incidentally, this issue arose after upgrading SophisticatedStorage, which was not an issue in older versions

**Comment by P3pp3rF1y** [comment]
Sure, but I don't think I have done anything so substantial there (other than adding layer that displays lock) and it works without rubidium extras. So given that I believe I am not doing anything wrong until they can tell me otherwise there's nothing to fix in sophisticated storage.

**Comment by P3pp3rF1y** [comment]
And actually I seem to have been looking at incorrect rubidium extra project and there's already a bug for exactly this on the one that I guess you use https://github.com/dimadencep/sodium-extra-forge/issues/29

**Comment by Dr-WeiAL** [comment]
Well, then wait for the other side to solve it, anyway, does not affect the normal use
