### ISSUE TITLE
Item displays on front of barrels too large

### ISSUE THREAD

**Issue by rckymtnrfc** [P3pp3rF1y/SophisticatedStorage#113]
![item displays](https://user-images.githubusercontent.com/6869242/208534576-556e354b-3900-4cf9-844d-81899d053360.png)

Minecraft 1.19.2
Forge 43.1.57 and up (not present in 43.1.55)
Soph Core - 0.5.34.190
Soph Storage - 0.6.15.266
Soph Backpacks - 3.18.37.762

This is happening with barrels (2 on left) and limited barrels (4 on right).  Blocks seem to display at the correct size but items are oversized.  Aside from looking off, it results in render hiding the item quantity that is displayed on limited barrels.

Does not seem to be present in Forge versions prior to 43.1.55 in my testing.

**Comment by P3pp3rF1y** [comment]
found out that this is caused by bug in forge which is going to be fixed by this PR https://github.com/MinecraftForge/MinecraftForge/pull/9231 I can't fix this on my side (only thing I can do is make every smaller including the blocks) so will need to wait for forge to fix.

**Comment by rckymtnrfc** [comment]
I thought it might be a Forge issue.  I assume the same bug is making items in the Farmer's Delight cutting board sit upright instead of laying flat.  I'll wait for the fix to be released in a future Forge version.

Thanks
