### ISSUE TITLE
Void Upgrade not working with vanilla hoppers (1.18.2)

### ISSUE THREAD

**Issue by Ganpan14O** [P3pp3rF1y/SophisticatedStorage#117]
I have a vanilla hopper pointing into the back of a north facing limited spruce iron barrel IV with a base tier void upgrade set to void overflow, only work with automation, and with a blank block filter. Instead of the expected behavior of it voiding the items that have full stacks in its inventory the items are stuck in the hopper. If I replace the hopper with a modded equivalent (PNCR Omnidirectional hopper) the void upgrade works in the expected way

**Comment by Ganpan14O** [comment]
Images of issue mentioned
![2022-12-29_22 09 29](https://user-images.githubusercontent.com/85914881/210033384-6ea8a5e4-74a7-41a7-965b-a23878e870f4.png)
![2022-12-29_22 09 37](https://user-images.githubusercontent.com/85914881/210033386-65a5215d-b8d6-4346-87e2-14c078544384.png)
![2022-12-29_22 09 45](https://user-images.githubusercontent.com/85914881/210033387-2f2ec876-ce50-45cc-9404-d127a1a61f12.png)

**Comment by P3pp3rF1y** [comment]
This was fixed some time ago
