### ISSUE TITLE
Sophisticated Storage / Productive Bees (sort of) duping issue.

### ISSUE THREAD

**Issue by jursamaj** [P3pp3rF1y/SophisticatedStorage#118]
I'm not sure where the issue is, so I'm reporting this to both mods.

Sophisticated Storage & Sophisticated Backpacks can add a crafting grid to storage items (chests, barrels, & backpacks).  This grid includes a button for "Balance Grid"/"Spread Grid", which attempts to arrange multiple of an item on the grid in even stacks.

Productive Bees has a Gene Sample item, which uses NBT tags to show what type of gene it contains, as well as a percentage value for that gene.

If I put multiple stacks of Gene Samples in the grid, with different genes and/or percentages, then use the balance/spread button, it will treat all of the samples as if they were interchangeable, and just change the quantity of each.  Thus, if I have a stack of 1 sample of "Weather Tolerance: Any (100%)" in the 1st grid slot, and 1 stack of 10 samples of "Productivity: High (1%)" in the 2nd slot, and "balance" them, I will end up with a stack of 6 "Weather Tolerance: Any (100%)" and a stack of 5 "Productivity: High (1%)".

Mod pack is ATM7
Soph. Storage 1.18.2-0.5.17.152
Soph. Backpacks 1.18.2-3.18.29.718
Soph. Core 1.18.2-0.5.13.132
Productive Bees 1.18.2-0.9.1.6

Cross reference: https://github.com/JDKDigital/productive-bees/issues/346

**Comment by P3pp3rF1y** [comment]
Actually posting my question here as well - if you try to do the same in regular crafting table do you get the same issue? I am only calling crafting tweaks compat layer here to get it rotated so it sounds more like some issue there which would manifest in regular crafting table as well.

**Comment by jursamaj** [comment]
@P3pp3rF1y The regular crafting table doesn't have the balance/spread button.

**Comment by P3pp3rF1y** [comment]
Found the issue, fixed it and released a while back, just forgot to close
