### ISSUE TITLE
Filter item and organization make error "unequal before and after item count" with stack upgrade  

### ISSUE THREAD

**Issue by IXOlex** [P3pp3rF1y/SophisticatedStorage#119]
Hello, I got this error when I try to sort my chest 
![2023-01-03_15 38 49](https://user-images.githubusercontent.com/108869257/210378930-25b85105-2087-4585-9f9a-f677a6eb38a4.png)
 With upgrade stack (any level of it), and it won't organize and get this error, or I have similar error like "infinite loop" some time

**Comment by P3pp3rF1y** [comment]
those are not this mods sorting buttons and that message isn't from this mod. Likely it's a quark one or some other sort mods which is not ready to sort sophisticated inventories.

**Comment by P3pp3rF1y** [comment]
What version is this actually?

**Comment by IXOlex** [comment]
It's 18.2 and forge was 40.1.92

**Comment by IXOlex** [comment]
> What version is this actually?
It's 18.2 and forge was 40.1.92

**Comment by P3pp3rF1y** [comment]
Searching by the message looks like you're using inventory profiles and they are not capable of sorting sophisticated inventories. Sorting sophisticated should be disabled in their config (I believe they have that option) in this case.

**Comment by IXOlex** [comment]
okay thx
