### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Durigonn** [P3pp3rF1y/SophisticatedStorage#121]
My ATM8 server crashes every couple minutes and upon joining with the message "Disconnected".
I was told this was an issue with XNET and Sophisticated Storage.
[crash-2023-01-10_10.02.14-server.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/10386672/crash-2023-01-10_10.02.14-server.txt)
edit: this is on 1.19.2

**Comment by P3pp3rF1y** [comment]
The only thing I can see here is that it crashed while trying to compare two items one of which had some capabilities which needed initializing and in that process it took way too long. if you can figure out what item that was I can look into this more, but without that information there's nothing much I could do here as this is standard method of comparing items used by forge and many other mods so not something that should be causing any issues at all.

**Comment by Durigonn** [comment]
I can't think of anything, but the last thing that someone on the server did was a 25x20 area with Hydroponic beds from Industrial foregoing growing Mystical Agriculture seeds connected to a Sophisticated Storage barrel with XNET, going from the barrel to an ME System from Refined Storage into a Crafter from RFtools. I have no idea if that is of any help, but thanks for answering.

**Comment by P3pp3rF1y** [comment]
closing this as this can't be recreated and I have also made some performance improvements in that part in the meantime so gathering of capabilities isn't happening here and likely even if the same case happened it wouldn't hang the server now.
