### ISSUE TITLE
Issue with quark chest compat recipes

### ISSUE THREAD

**Issue by enigmaquip** [P3pp3rF1y/SophisticatedStorage#123]
<https://github.com/P3pp3rF1y/SophisticatedStorage/blob/1.19.x/src/generated/resources/data/sophisticatedstorage/recipes/acacia_chest_from_quark_acacia_chest.json>
datagen seems to have broken on these and as such the recipes are broken.
I would also suggest doing an item exists condition instead of a mod loaded condition as the chest replacement is a quark config setting

**Comment by zeziba** [comment]
Noticed the same thing too.

The ATM team added the following to their erroringRecipes.js for kubeJS to fix it.

Lines 166-93
```

  // sophisticated storage / quark chest compat
  ['acacia', 'birch', 'crimson', 'dark_oak', 'jungle', 'oak', 'spruce', 'warped'].forEach(wood => {
    event.addJson(`sophisticatedstorage:recipes/${wood}_chest_from_quark_${wood}_chest`, {
      "type": "minecraft:crafting_shapeless",
      "conditions": [
        {
          "type": "forge:mod_loaded",
          "modid": "quark"
        },
        {
          "type": "sophisticatedcore:item_enabled",
          "itemRegistryName": "sophisticatedstorage:chest"
        }
      ],
      "ingredients": [
        {
          "item": `quark:${wood}_chest`
        },
        {
          "item": "minecraft:redstone_torch"
        }
      ],
      "result": {
        "item": "sophisticatedstorage:chest",
        "nbt": `{woodType:\"${wood}\"}`
      }
    })
  });
```

Don't know if you want to fix it but it has already been done so you could just put a mention in the main page about it along with a link to the above from where ever they got it.

**Comment by P3pp3rF1y** [comment]
Just released version with fix on curseforge
