### ISSUE TITLE
Barrel Item Icon Size

### ISSUE THREAD

**Issue by deaddraggz** [P3pp3rF1y/SophisticatedStorage#124]
The size of the icon of modded items on the barrels is
 too large and covers up the count on the barrel.![Screenshot (16)](https://user-images.githubusercontent.com/33603173/212523063-ec08fb7c-50bc-4876-8fb1-10e53c142090.png)

**Comment by P3pp3rF1y** [comment]
This is caused by a bug in forge that was fixed in forge 43.2.3 so just get that or newer and you're good
