### ISSUE TITLE
Issue: Incompatibility with functional storage ?

### ISSUE THREAD

**Issue by BigKid1973** [P3pp3rF1y/SophisticatedStorage#129]
I had a working functional storage (drawer system) setup in my base (actually 2 - since the second one was too far away to link). Once I started playing around with the sophisticated storage controller I noticed two strange things:
- Also I had unlocked one barrel and had set no memorized slots in it - I was not able to get the controller to put "unknown" stuff in there. Inserting stuff already in any barrel did work - including the unlocked one
- I then noticed that my functunial storage setup stopped working as intended - it started to reject everything into it's only unlocked drawer - also the other drawers still had space left
- Once I removed the sophisticated storage controller - the functional storage started working again

Exact setup:
- several locked functional drawers , one unlocked one to accept unknown stuff (and then pipe it into a functional storage barrel - that barrel was NOT linked to the sophisticated stoarage controller) - all this 2 times
- several locked barrels with memorize set to all slots, one unlocked with no memorized slots, a sophisticated drawer controller, all linked to the sophisticated controller
- a sophisticated backpack on my back

Is this a known issue ?

**Comment by BigKid1973** [comment]
It seems not to be related to sophisticated storage. Its an issue with functional storage only… At least it is happening even when no sophisticated storage controller is around

**Comment by P3pp3rF1y** [comment]
thanks for info, closing
