### ISSUE TITLE
UI in >144 slots does not render properly

### ISSUE THREAD

**Issue by Hermeleginda** [P3pp3rF1y/SophisticatedStorage#13]
Core 1.18.2 - 0.1.0.19
Sophisticated Storage 1.18.2 - 0.0.11.26

Tried it both for 180 and 168 slots. It is functional though.

![visual bug](https://user-images.githubusercontent.com/79456180/169540882-83891d6a-7b4e-4c13-a77a-1712269f0b6f.png)

**Comment by MattB70** [comment]
For the dev: Unless someone has created a library to handle scrolling inventories, you should probably just cap the limit. Seeing this problem pop up again brings back some bad memories. Don't try and solve it lol

**Comment by P3pp3rF1y** [comment]
@MattB70 I am actually in the process of adding scrollable inventory so that shouldn't be an issue anymore after that.

**Comment by MattB70** [comment]
Let me casually star this repo for later then. I'm excited to see how you implement it. Last I saw it attempted was 1.12.
Excited for it and for this mod.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version of sophisticated core / storage
