### ISSUE TITLE
Shulker box wont open directly from inventory

### ISSUE THREAD

**Issue by Jayerd** [P3pp3rF1y/SophisticatedStorage#130]
Im playing on "sophisticatedstorage-1.19.2-0.6.16.276" and the right click to open feature doesnt work it just plays the shulker box open sound and nothing else

**Comment by KirbyBrasse** [comment]
Isn't it because it's another mod that open shulkerbox in inventory ?

**Comment by P3pp3rF1y** [comment]
this is intentional, shulker boxes are not supposed to open in inventory, you have backpacks for that.
