### ISSUE TITLE
Storage Controller ghost block

### ISSUE THREAD

**Issue by AdamV191** [P3pp3rF1y/SophisticatedStorage#134]
Kia Ora,

I had several chests linked with a storage controller. When I broke the controller and then placed an Ae Import bus against where the Storage Controller block would have been, it acted as if the block was still there and started to import the items into the AE system. 
Thanks :)

**Comment by P3pp3rF1y** [comment]
I am unable to recreate it just doesn't do anything. I will need exact steps on how I can recreate this bug, I am not even sure how you can place the import bus to import from that place when it doesn't have anything to be placed against, but I tried a few variants with placing first before breaking / placing stone in that place and then placing import bus all that produced expected result of not importing anything.

**Comment by P3pp3rF1y** [comment]
closing given no additional info was provided in a very long time
