### ISSUE TITLE
Sorting in Crafting station can delet items

### ISSUE THREAD

**Issue by Lugaboiy** [P3pp3rF1y/SophisticatedStorage#137]
what is the problem?
items get displayed wrong in Crafting stations
if you want it to be displayed correctly it can delete items

Setup:
golden chest (with Stack upgrade tier 3) next to crafting station
![image](https://user-images.githubusercontent.com/112725778/226197934-13219947-dce8-49f6-99c0-4d785bd58a18.png)
![image](https://user-images.githubusercontent.com/112725778/226197991-58f15207-022e-480b-b44d-8b6b653e84cd.png)

if i sort the inventory in the chest it gets displayed wrong
if i do it in the crafting station it decompresses all the stacks into stacks of 64 and every stack taht doesnt fit gets deleted.

when i sort in the chest 
![image](https://user-images.githubusercontent.com/112725778/226198164-334b651f-d95c-472d-ad83-6de7c47d7a0f.png)
![image](https://user-images.githubusercontent.com/112725778/226198169-4919b58c-b5ee-4ff4-ab7e-adc8287a947d.png)

when i sort in the crafting station (as you can see the rest of the cobble was deleted because it had no space in the inventory)
![image](https://user-images.githubusercontent.com/112725778/226198102-e4f14545-38b5-4376-a59d-fc3546355fec.png)
![image](https://user-images.githubusercontent.com/112725778/226198109-6363b84f-361b-4478-9091-b3d671f3f483.png)

waht i just now relized is that the tinkers crafting station probably cant display anythinmh bigger then 128(0 to 127)
also just tested this i can display anything up to 127 items after that it dissapears.

Modpack ATM7 To the Sky
(dont know if it is a problem with sophisticated Storage, Tinkers crafting station, or the inventory sorter that allows items to be deleted.)

**Comment by P3pp3rF1y** [comment]
So yeah this is crafting station not ready for stacks larger than 64 as well as sorter not ready either (but there it may be because crafting station is telling it that the slots have max of 64). So there's nothing I can do on my side to fix.
