### ISSUE TITLE
Controller can laag the whole game

### ISSUE THREAD

**Issue by mikaba-eu** [P3pp3rF1y/SophisticatedStorage#138]
If the controller don't find a chest there the input can goes to, this can course a heavy lag.

**Comment by P3pp3rF1y** [comment]
could you give me more info on how I can recreate that? Also on what version that is that you are experiencing this in or if you have a Spark trace or something similar based on which I could see what's happening there?

I can't recreate and this is the first time I am hearing about any performance issues there so definitely need more info here.

**Comment by P3pp3rF1y** [comment]
closing as there was no additional info provided, I can't recreate and haven't heard from anyone else about anything like this.
