### ISSUE TITLE
baseSlotLimitMultiplier for LimitedBarrel

### ISSUE THREAD

**Issue by mikaba-eu** [P3pp3rF1y/SophisticatedStorage#139]
Can we set a higher value for the baseSlotLimitMultiplier please?

https://github.com/P3pp3rF1y/SophisticatedStorage/blob/e820deb76821de2e4e167b1dc39d5daaaf799779/src/main/java/net/p3pp3rf1y/sophisticatedstorage/Config.java#L210

**Comment by P3pp3rF1y** [comment]
Just released version with changed limit on curseforge
