### ISSUE TITLE
New compression upgrade causes crash when the wrong item is put in a slot

### ISSUE THREAD

**Issue by DanL3m0n** [P3pp3rF1y/SophisticatedStorage#145]
When using a limited barrel with the new compression upgrade, putting the wrong item in a slot can cause the game to instantly crash. For example, putting an ingot in the top slot of a limited barrel 3 instead of a block, or accidentally putting in a non-compressible item can cause a crash.

I am playing on a slightly modified All The Mods 7: To The Sky modpack, so it could be a compatibility issue.

Here is the crash text from the launcher:
The game crashed whilst unexpected error
Error: java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.BlockItem (net.minecraft.world.item.AirItem and net.minecraft.world.item.BlockItem are in module minecraft@1.18.2 of loader 'TRANSFORMER' @25d911a)
Exit Code: -1

Crash Report:
[crash-2023-04-03_19.31.48-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/11143637/crash-2023-04-03_19.31.48-client.txt)

**Comment by DanL3m0n** [comment]
It's crashed this way at least a dozen times, this time the text the launcher gives after a crash was different, but looked very similar:
The game crashed whilst unexpected error
Error: java.util.concurrent.CompletionException: java.lang.ClassCastException
Exit Code: -1

[crash-2023-04-07_19.30.05-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/11182316/crash-2023-04-07_19.30.05-client.txt)

Additionally, I found another issue that I assume is the result of some recipe conflicts. I have a drawer with a compression upgrade that I am using to store zinc. When I put the ingots in first, it does not allow me to convert to blocks, only to nuggets. When I first tried to put a block in, it did not work and caused the crash described above. I added a recipe for zinc blocks to ingots in the config and that partially fixed the issue, because now it can convert between zinc ingots and blocks, but something occasionally causes it to forget the recipe and it breaks again, only allowing to convert ingots and nuggets, but not blocks. (I hope this explanation is clear enough, it's a bit hard to explain)

**Comment by P3pp3rF1y** [comment]
This is crashing in rubidium code for some reason and I am unable to recreate with just sophisticated storage and rubidium in a pack and trying out with different items so I am guessing this may be related to that recipe issue you mention causing some kind of really incorrect interaction. Could you share what jei shows for compacting zinc ingots into block and uncompacting zinc block? there may be possibly multiple recipes there for this as well so seeing those could help.

**Comment by DanL3m0n** [comment]
Yeah, there's several recipes in JEI that are conflicting.

![image](https://user-images.githubusercontent.com/129808248/230740019-57332f78-6e12-432f-ba08-60e4e9121938.png)
![image](https://user-images.githubusercontent.com/129808248/230740025-e1c1b2a5-5f27-4769-9f7a-cdf5efb3f0ad.png)
![image](https://user-images.githubusercontent.com/129808248/230740058-50b72d71-0d51-422b-9826-92db798efe71.png)
![image](https://user-images.githubusercontent.com/129808248/230740065-05029466-8d97-4ed9-8f7a-d3af0892f228.png)

There are also identical recipes that I didn't include that are with the create variants of the block and ingot.
One weird thing is that in this modpack at least, the create versions of the ingot, block, and nugget are not shown in JEI, only in crafting recipes.

Also, here's a video demonstrating the issue with the drawer in question.
https://drive.google.com/file/d/1pgH0YxemYOkLv9bIz6uFCy6zmGUap0Zg/view?usp=share_link

**Comment by DanL3m0n** [comment]
I would say you should try it with Sophisticated Storage, Rubidium, Create, and All The Ores and see if that makes it crash, as those are all the easy to spot contributors to the issue.

**Comment by P3pp3rF1y** [comment]
closing given I had no additional reports of anything like this so must have been something that was extremely rare or was indirectly fixed since.
