### ISSUE TITLE
Compression upgrade voids items when inserting into a full slot

### ISSUE THREAD

**Issue by alterNERDtive** [P3pp3rF1y/SophisticatedStorage#149]
Once you add a compression upgrade and put something in there (let’s say, iron), it starts voiding items once the item slots reaches max stack size. That happens on both Limited Barrels (with nowhere to stuff the extra items) as well as Chests/Barrels (ignoring the empty slots right outside the ones reserved for compression).

![image](https://user-images.githubusercontent.com/53827887/230724358-c732733f-d1ca-45e7-bff6-7e01b0be2ad5.png)
![image](https://user-images.githubusercontent.com/53827887/230724370-9dd82dd3-e18c-45e4-a53a-c3f89fc1d08a.png)
![image](https://user-images.githubusercontent.com/53827887/230724374-8115ad80-5ef2-429f-b6f5-57e9696e7edb.png)
![image](https://user-images.githubusercontent.com/53827887/230724387-3a1c1829-e847-4efc-b126-2c83a389e083.png)

**Comment by P3pp3rF1y** [comment]
Just tried this in test world and I am unable to recreate so I will need more info on stuff like mod versions (storage and core) and possibly need to have this narrow down to with what other mod this issue happens (minimal set of mods).
Also there was a fix to core which may have fixed this issue so make sure you have the latest core in the pack

**Comment by alterNERDtive** [comment]
This would be the versions

![image](https://user-images.githubusercontent.com/53827887/230736870-68d4c818-fdc5-4ae3-9fde-77bda007e87c.png)

I’ll try a minimal installation, but probably won’t get to it today.

Also which Forge did you test with? In case that ends up mattering.

**Comment by alterNERDtive** [comment]
~~Clean install with nothing but Sophisticated Core/Storage (same versions as above) does not have the issue.~~ Technically incorrect, see below.

Oh boi, here I go down the rabbit hole …

**Comment by alterNERDtive** [comment]
Installing a clean instance of Vault Hunters 3ʳᵈ edition, then adding Sophisticated Storage (and updating the other Sophisticated mods to latest) _does_ end up with the bug.

Edit: found the culprit, doing further testing to narrow it down.

**Comment by alterNERDtive** [comment]
So, it is Compressium, and it _only_ happens with stuff that can be compressed past what’s in the container. E.g. putting more Iron Blocks into an iron nugget/ingot/block barrel will void stuff. Putting more Echo gems of any description into a Limited Barrel Ⅲ will not void.

BUT … it is _not limited to Compressium blocks_. The Compression Upgrade will happily compress anything you put into the container as long as it can be compressed further; and it apparently does not check if there is actually _space to put the result_.

I guess you’ll know how to take it from here :)

**Comment by provet1** [comment]
Got the same issue with this setup:
Netherite chest with 2 filters and 1 compression, I input-filter iron blocks and output-filter iron nuggets.
Either manually adding or using a hopper, items above a limit are removed (for me the limit are 55 iron blocks: going to 56 turns it down to 55 voiding the last block)

**Comment by P3pp3rF1y** [comment]
I wasn't able to recreate this in dev, but have actually fixed issues with slot limit calculation in that area that caused duplication / loss issues so this is very likely fixed with that as well

**Comment by alterNERDtive** [comment]
Appears to be fixed in the latest version, tyvm 👍
