### ISSUE TITLE
Warning message for too many items when destroying a chest/barrel tells you to use literal `Shift` instead of sneak

### ISSUE THREAD

**Issue by alterNERDtive** [P3pp3rF1y/SophisticatedStorage#150]
When you try breaking a Chest/Barrel with too many items in it, the mod will warn you about that and tell you to use `Shift` if you want to ignore that and break it anyway.

You actually have to break it while sneaking. The _default_ is still `Shift`, obviously.

**Comment by P3pp3rF1y** [comment]
this was fixed to refer to sneaking a few releases back I just didn't close it back then
