### ISSUE TITLE
Mod Conflictions

### ISSUE THREAD

**Issue by Akumi22** [P3pp3rF1y/SophisticatedStorage#152]
Hey just wanted to let you know that when Chipped 1.19.2 is installed with your mod that all your barrrels become ghost blocks and can sometimes cause the game to crash when interacting with them. i worked the the apex team and we couldnt find a fix figured id let you know!
![20230410_123104](https://user-images.githubusercontent.com/130395490/230962217-06a87feb-d73b-4d81-86f0-eec784ccb062.jpg)

**Comment by P3pp3rF1y** [comment]
fixed in latest release on curseforge
