### ISSUE TITLE
JEI gets in the way of right-hand settings tabs

### ISSUE THREAD

**Issue by paulsd95** [P3pp3rF1y/SophisticatedStorage#159]
![image](https://user-images.githubusercontent.com/22594726/232187464-64c4c2b8-9c5f-43c9-a85c-4e54c230b167.png)

So if I attempt to use a storage chest or barrel with a wide enough window (works best with Netherite) with either low resolution or high GUI scale, the settings tabs on the right when opened will overlap with JEI. Trying to click there will instead interact with the JEI item behind it, requiring closing the JEI overlay to interact with the settings item correctly.

Strangely this does not happen with Sophisticated Backpacks
![image](https://user-images.githubusercontent.com/22594726/232187811-3dd91e4b-fe21-4c1f-8e30-966e3b130733.png)
![image](https://user-images.githubusercontent.com/22594726/232187836-445e2530-a37b-4a5f-b4c4-e375d16c529b.png)
so there seems to be a non-parity going on here.

**Comment by brisingraerowing** [comment]
This happened in an earlier MC version due to a bug in the JEI plugin. I suspect there's a similar issue going on here.

**Comment by P3pp3rF1y** [comment]
This works for me correctly in all versions so yeah I would suspect it was a bug in JEI that got resolved. I am closing it now, but if you happen to recreate and confirm with JEI that it's not their issue feel free to create a new issue for that.
