### ISSUE TITLE
Drawer refuses to accept more items

### ISSUE THREAD

**Issue by bbf** [P3pp3rF1y/SophisticatedStorage#160]
Hello,

I'm not sure of  what's going on, but I have the following issue on my server: drawers refuse to accept more items.

I'm running  ATM-8 (latest 1.0.15) and have even tried to manually update to the latest versions of storage/backpack/core to no avail.

I have several drawers that are connected to a controller, with extensions, and even a Refined Storage external bus connected to an extension. Among my drawers I have some with no upgrade, some with void upgrades, some with storage upgrades and some with both types of upgrades.

I don't know what is causing the issue, but I tried to isolate to find any common pattern. After the drawer is bugged, even if I take down the controller, the drawer still refuses to accept more items.

![image](https://user-images.githubusercontent.com/158033/232652649-dce885ec-e172-4b45-b116-00abf76d0c76.png)

If I try to instead of depositing, to withdraw first something, and then deposit, it sometimes works. There's some temporal connection here as well, because after some arbitrary time, the drawer will stop working again. I'm currently leaving the controller down to see if without it I can cause the same issue. If not, I imagine it could be something interacting with the controller.

How can I help you further isolate the problem? Would a save share help? I can even dump the NBT from a drawer in a world save if you want, just let me know what I should be looking for.

**Comment by Mitchell5200** [comment]
You reported a Functional storage drawer to the Sophisticated storage dev? wrong mod unfortunately.

**Comment by bbf** [comment]
Oh, sorry, my bad :)
