### ISSUE TITLE
Compression Upgrade can copy items

### ISSUE THREAD

**Issue by Dr-WeiAL** [P3pp3rF1y/SophisticatedStorage#165]
This bug was discovered while making the translation
A very serious bug of copying items

First, put 64 iron ingots into it
![BOLN9UX@$Y$7X79CETVQ(SK](https://user-images.githubusercontent.com/47446553/233780821-5ba3ab98-aaed-45f6-bb56-ab3088dfd125.png)

Then, destroy it
![image](https://user-images.githubusercontent.com/47446553/233780840-a71d4b1d-2274-40d3-84cc-c027a08ec812.png)

It drops these items
![image](https://user-images.githubusercontent.com/47446553/233780845-5f6cd2d3-8ae1-45b5-874f-5e2e9860fd6e.png)

**Comment by Dr-WeiAL** [comment]
Uh...I'm still having this problem after testing with development, is it not uploaded yet?

**Comment by P3pp3rF1y** [comment]
what do you mean when you say you're testing with development? Where have you downloaded the mod from?

**Comment by Dr-WeiAL** [comment]
Machine translation may be wrong, I build from 1.18.x-dev branch

**Comment by P3pp3rF1y** [comment]
this requires latest version of core though

**Comment by Dr-WeiAL** [comment]
Well thank you very much!

**Comment by P3pp3rF1y** [comment]
Fixed in the latest core which is released on CF
