### ISSUE TITLE
connectedness compatibility

### ISSUE THREAD

**Issue by Dr-WeiAL** [P3pp3rF1y/SophisticatedStorage#179]
After installing [connectedness](https://www.curseforge.com/minecraft/mc-mods/connectedness) and enabling the built-in Default CTM resourcepack, the barrel textures error
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/47446553/239c78a0-dd2a-418c-8d18-a18927dc1c58)

**Comment by P3pp3rF1y** [comment]
Please report to them, I am not doing anything special other than loading custom models and they appear to change a ton of vanilla stuff so it's on them to fix their code.

**Comment by P3pp3rF1y** [comment]
Also the other hint is that multiple other mods that use custom baked models have rendering issues when this mod is in the pack.
