### ISSUE TITLE
Item deleting with sort 

### ISSUE THREAD

**Issue by knowfear1337** [P3pp3rF1y/SophisticatedStorage#18]
has only happened twice 
using a spruce barrel upgraded to iron with the lowest tier stack upgrade 
sorting with middle click has caused the upper half contents to get deleted 

playing the DW20 1.18 pack ver 1.2.0 
sophisticatedcore-1.18.2-0.1.0.19.jar
sophisticatedstorage-1.18.2-0.0.10.22.jar

both times the barrels have been close to full and middle clicked to sort after dumping stuff in 
and they seem to work fine after it happens too as it was 2 different barrels

**Comment by P3pp3rF1y** [comment]
Are you using some sorting mod in the modpack?

**Comment by knowfear1337** [comment]
I'm not up-to-date on all the mods especially the newer ones i haven't heard of before but Quark may still have it and MouseTweaks-forge-mc1.18-2.21.jar
there are a few other storage mods in the pack too but at least there is a full list on the FTB website

**Comment by Zarkazm** [comment]
Came here to report this as well.  Same modpack, same versions.  In my case it was a Spruce Diamond Chest, with a Tier 4 Stack Upgrade.  Opened the chest and everything had been "unstacked" back to their defaults of 64x per stack.  Used the middle click sort and some of the ores disappeared.  It looks like the middle click sorting is done by a standalone mod called Inventory Sorter, v19.0.0.

**Comment by P3pp3rF1y** [comment]
Can you double check that Sophisticated Storage sorting is also mapped to middle click? Should be by default and should have higher priority but it sounds like either it is mapped to something else or some other mod handles sorting with even higher priority

**Comment by P3pp3rF1y** [comment]
So yeah this is caused by InventorySorter and I have commented in a bug that's created for this on FTB issue tracker https://github.com/FTBTeam/FTB-Modpack-Issues/issues/838 . Ideally InventorySorter would fix its bug in compatibility implementation and this would be prevented, but while this is still not fixed dw20 modpack should get an update to inventory sorter config to prevent it from working on sophisticated screens.

**Comment by knowfear1337** [comment]
That's cool, i just got on to check the keybindings and they were both on MMB, if i set the sophisticated buttons to something else in the meantime untill they update the pack hopefully that will help ? 
loving the mods too btw 10/10 just for how amazing the feeding upgrade is in the backpack XD

**Comment by P3pp3rF1y** [comment]
I tested an hour ago that if both sophisticated storage and inventory sorter are set to middle mouse sophisticated storage logic kicks in first and sorts it properly. So I would say just don't remove that and you are good.
