### ISSUE TITLE
JEI compat related error in log (1.19.2)

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedStorage#180]
Minecraft: 1.19.2
Forge: 43.2.10
Sophisticated Storage: 1.19.2-0.7.8.366
Sophisticated Core: 1.19.2-0.5.54.261
-----------------------------------------------------
Hi, I'm working on my own modpack and I found something weird/strange or maybe it's nothing important in my log file durring registering recipes (If you will need full log, I can post it here aswell):

https://pastebin.com/49EBfEry

EDIT: I also found out that when in creative mode, normally you can shift+left click to destroy/remove/clear player inventory of anything but after installing Sophisticated Storage, you can not do that anymore, so I disabled Sophisticated Storage and now it's working normally.

**Comment by P3pp3rF1y** [comment]
That bug looks like incompatibility with new version of JEI, I will take a look at that with some fixes I need to do for new version of JEI anyway. As for shift clicking to clear inventory that just works for me without any issues so I am guessing something else in your pack is interfering there.

**Comment by P3pp3rF1y** [comment]
Actually I took a look at this and no issue is happening for me in dev or in a massive pack I play at the moment. The best guess I have is that in your pack tier upgrades have changed recipe somehow or are removed or something similar so I will need more info on that so that I can recreate.

**Comment by ghost** [comment]
It was happening with versions I mentioned, if it's not happening anymore, I'm closing this issue

**Comment by ghost** [comment]
Sadly, I can not reproduce that because I already replaced for diff mod.
