### ISSUE TITLE
the compression upgrade is still have some questions

### ISSUE THREAD

**Issue by Alartias** [P3pp3rF1y/SophisticatedStorage#186]
The capacity of subordinates is ten times that of superiors, but most things just nine or four times. So when the superiors are full, I could continue to put in the subordinates and the superiors didnt increase. However then I put out the subordinates, the superiors will decrease. Till now there is no serious bug. but because of the decrease of the superiors, it looks like that I could put in the superiors, but when I try this, the item is lost, just like add the void upgrade.

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
