### ISSUE TITLE
Compatibility with Quark's “Expanded Item Interactions”

### ISSUE THREAD

**Issue by Huantanhua** [P3pp3rF1y/SophisticatedStorage#187]
**Minecraft: 1.19.2
Forge: 43.2.11
Sophisticated Storage: 1.19.2-0.8.5.402
Sophisticated Core: 1.19.2-0.5.57.275
Quark：1.19.2-3.4-402**
Vanilla Shulker Boxes can be opened with right click in your inventory in Quark mod. Sophisticated Storage Shulker Boxes has a tooltip but can't be opened in inventory.

**Comment by P3pp3rF1y** [comment]
This is intended for sophisticated shulker boxes, if you want something you can open in your inventory you should use backpacks instead. And opening in inventory would require a whole lot of additional dev work so this is something I am not going to add.

**Comment by TheFantasticLoki** [comment]
Has the stance on this possibly changed? I would love to be able to open sophisticated shulkers inside inventories without having to place them since we can use them in backpacks and ender chests and such.
