### ISSUE TITLE
Compression Upgrade allows entire barrel to be compressed.

### ISSUE THREAD

**Issue by kalutro** [P3pp3rF1y/SophisticatedStorage#194]
Came across a couple neat bugs and spent about 20 minutes trying to recreate them.

Ingredients:
Netherite Barrel x1, Compression Upgrade x2, compressible items (optional)

Directions:
1. Place down barrel.
2. Open barrel and place the first Upgrade in the first upgrade slot. (Aside: The slot textures don't show up sometimes.)
3. Place the second Upgrade in the second upgrade slot.
4. Pickup the second Upgrade and, while the Upgrade is on the mouse, click the Upgrade in the first upgrade slot.
5. Place the second Upgrade into your inventory.
6. Remove the first Upgrade.

This will fill the barrel with compressible slots. If you place a compressible item into the barrel, you will be able to compress it up to 127 (max signed byte) slots. The final five slots will be a red X. I assume this is simply an overflow.

Since ATM8 comes with an NBT viewer, you can see that step four causes the value of "firstInventorySlot" to be copied to the first Upgrade. This may be the cause of the bug. Another side effect of this causes you to not be able to place the Compression Upgrades back into the barrel. You will receive an error saying, "There are no additional slots this compression upgrade can manage." The barrel can be reset by breaking and replacing it.

The second bug is similar, except you swap which upgrade you pick up.

Directions:
1. Place down barrel.
2. Open barrel and place the first Upgrade in the first upgrade slot.
3. Place the second Upgrade in the second upgrade slot.
4. Pickup the first Upgrade and, while the Upgrade is on the mouse, click the Upgrade in the second upgrade slot.
5. Place the first Upgrade into your inventory.
6. Remove the second Upgrade. This causes the second set of compressible slots to become permanent.
7. Place the first Upgrade back into the first upgrade slot.
8. Place the second Upgrade back into the second upgrade slot. This causes the second Upgrade to add five slots beyond the permanent ones created in step 6.

You can continue this to get as many slots as you want. The permanent slots can only be reset by breaking and replacing the barrel.

Similar to the first bug, the value of "firstInventorySlot" on the first upgrade gets copied to the second upgrade. I infer this causes the bug to occur.

I found this bug in ATM8 1.0.19b, which includes sophisticatedcore-1.19.2-0.5.54.261 and sophisticatedstorage-1.19.2-0.7.8.366.

I really like the idea of the Compression Upgrade, but it would be better if there was an Advanced version that could go up to 10 or more slots, specifically for packs like this. You could turn this bug into a feature.

**Comment by P3pp3rF1y** [comment]
this is fixed with latest releases of sophisticated core and sophisticated storage
