### ISSUE TITLE
Crash with LATEST versions of Sophisticated Core AND Sophisticated Storage FORGE 1.19.2

### ISSUE THREAD

**Issue by Minebrah** [P3pp3rF1y/SophisticatedStorage#197]
https://gist.github.com/Minebrah/e6165cef0cc00b06626ab55c8b5f448b

https://gist.github.com/Minebrah/04b6e8b66e0611946f7e0b3383840a64

**Comment by P3pp3rF1y** [comment]
it is crashing because you haven't updated sophisticated backpacks to the latest version so just update that
