### ISSUE TITLE
Feature Request: Abstract Texture Features for chests.

### ISSUE THREAD

**Issue by Rosethorns** [P3pp3rF1y/SophisticatedStorage#20]
Hi P3pp3rF1y

Currently there is no way for me to assign a different `tintable_main` (for example) to different chest materials.
While you can have different `normal` textures per chest material. There is only one `tintable_main`, and `tintable_accent` for all chest materials.

This makes individual changes to chests a exercise in compromise currently.

My own need for such a feature and a good example of why I think this should be considered is Quark chests which are considerably different textures per material type.

Thanks for reading.

-Rorax

**Comment by P3pp3rF1y** [comment]
I am in favor of adding this, but just one question before I do so - at the moment the logic would basically remove woodtype as soon as you apply both tints which means that if two tints get applied to any chest type they would use the generic textures for the tints. 
Are you actually thinking of also having the two tint variant chests (both main and accent tint applied) per wood variant they are based on?

I hope that I am fairly clear with that question, but reading it back it may be a bit confusing so let me know if you would like me to explain that a bit more.

**Comment by Rosethorns** [comment]
So I haven't written out the specifics. But I believe you could get away with this as two tints per wood type **as needed**

What I mean by this is that you allow the tint textures to be specified in the model file. Right now you have one model file that just points to the chest loader for all chests and if you abstracted out one model per material type
```
"tintTexture": {
     "main": "sopisticatedstorage:block/tintable_main",
     "accent": "sopisticatedstorage:block/tintable_accent",
}
```
Or something to that effect. 
I could simply come along as a pack author and add my own resource and change `"main":` to some other texture.

If you wanted to you could maybe even go further and allow any material type to be a json model so I could come along and add other chest material chests myself from unsupported modded woods.

Thats probably surplus to what I am saying here though.
Right now to recap I'm asking for 1 model file per material type
And texture specification in that JSON as exampled above. (yours could just use the same two textures you current have to avoid bloat.)

**Comment by P3pp3rF1y** [comment]
Just added this in c62cd3b61e0035dcd584fc0154caa7a3505ad920 - allows defining all the textures used for rendering the chest per wood type e.g. birch is defined here:

https://github.com/P3pp3rF1y/SophisticatedStorage/blob/1.18.x-dev/src/main/resources/assets/sophisticatedstorage/storage_texture_definitions/birch_chest.json

and as you can see there you can reference parent definitions with this one being default for chest "by default"

https://github.com/P3pp3rF1y/SophisticatedStorage/blob/1.18.x-dev/src/main/resources/assets/sophisticatedstorage/storage_texture_definitions/chest.json

**Comment by P3pp3rF1y** [comment]
Already released for some time. Closing...
