### ISSUE TITLE
Netherite Shulker Box，Barrel and Chest are not immune to fire and explosions like Netherite Backpack.

### ISSUE THREAD

**Issue by Huantanhua** [P3pp3rF1y/SophisticatedStorage#204]
Netherite Shulker Box，Barrel and Chest are not immune to fire and explosions like Netherite Backpack. And is it possible to add Tank Upgrade and Everlasting Upgrade in the future？

**Comment by P3pp3rF1y** [comment]
This is added in the latest release on CF
