### ISSUE TITLE
Configuration Tool Causes irreparable crashing 

### ISSUE THREAD

**Issue by Saphirebuterfly** [P3pp3rF1y/SophisticatedStorage#207]
If you craft the configuration tool for the drawers, the game immediately crashes.  Try to get back into the game and it will autocrash every time you attmept to open the game.  There is no hope of saving the game after that as you cannot get in to get the tool out of your inventory even in creative mode.

**Comment by P3pp3rF1y** [comment]
You haven't mentioned anything about version or the crash log itself but I will have a wild guess that you're playing with 1.20.1-0.8.27.465 and you have rubidium in the pack which is mentioned at the top of the crashlog. If that is the case I added compatibility with rubidium in the latest version released yesterday.

**Comment by P3pp3rF1y** [comment]
closing this one as it was most probably related to rubidium and that has been solved for quite a while
