### ISSUE TITLE
Sophisticated Backpacks and Chests don't display tooltips or respond to JEI Use/Recipes keys...

### ISSUE THREAD

**Issue by Gantros** [P3pp3rF1y/SophisticatedStorage#21]
Describe the bug
When viewing the contents of the backpack, no tooltip information is displayed nor does JEI display uses or recipes when the appropriate key is pressed (R/U by default). Transferring the item/stack from the Sophisticated storage (Backpack or Chest) to regular inventory restores the tooltip within the regular inventory and JEI R/U functions. Barrels do not appear affected by this issue.

To Reproduce

Open backpack/chest
Hover mouse over any item/stack and/or click R/U on any item/stack (if JEI is installed)
3.) Observe issue
Expected behavior
I expected tooltip information and JEI Use/Recipe info when requested.

Screenshots
![2022-06-01_11 57 37](https://user-images.githubusercontent.com/63207219/171483810-290898d4-59dd-4a8b-8f5a-0b3225c0888d.png)
![2022-06-01_11 57 39](https://user-images.githubusercontent.com/63207219/171483815-1eda938f-7d24-4fab-a8a5-cf9caac4bd09.png)
![2022-06-01_11 58 01](https://user-images.githubusercontent.com/63207219/171483817-b61c502a-3edd-4c10-8f4d-937b60c06cfd.png)
![2022-06-01_11 58 04](https://user-images.githubusercontent.com/63207219/171483820-b5637bcb-5cba-4344-983d-0a1822cd5a65.png)

Versions
Minecraft version 1.18.2
Forge version 40.1.22
Sophisticated Core 1.18.2-0.2.5.28
Sophisticated Backpacks 1.18.2-3.17.2.588
Sophisticated Storage 1.18.2-1.0.6

**Comment by P3pp3rF1y** [comment]
fixed in the latest sophisticated core on curseforge
