### ISSUE TITLE
Inventory disappears when opening chest. Items removed from chest Disappear

### ISSUE THREAD

**Issue by YF3686** [P3pp3rF1y/SophisticatedStorage#211]
when opening chest almost all items disappear from inventory. anything removed from chest disappears from inventory after closing the chest. Item doesn't return to chest. Tried on a regular minecraft installation with just Sophisticated storage, backpacks and core and issue still occured. 
![screenshot_2](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/115881638/c64e9eac-aff8-4af7-bcd7-06dde3d99849)
![screenshot_1](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/115881638/57d21b5e-86de-4add-b802-05094f3efb04)

**Comment by P3pp3rF1y** [comment]
Just tried that and I don't see any issue. Items put in chest just stay there until you take them out so I will need more info on how exactly I could recreate this and please make sure you are also testing that with the latest versions of storage / core.

**Comment by P3pp3rF1y** [comment]
closing given no response

**Comment by Yveb** [comment]
> Beim Öffnen der Truhe verschwinden fast alle Gegenstände aus dem Inventar. Alles, was aus der Truhe entfernt wurde, verschwindet aus dem Inventar, nachdem die Truhe geschlossen wurde. Der Gegenstand kehrt nicht in die Truhe zurück. Habe es mit einer regulären Minecraft-Installation mit nur anspruchsvollem Speicher, Rucksäcken und Kern versucht und es trat immer noch ein Problem auf. ![Screenshot_2](https://private-user-images.githubusercontent.com/115881638/248553287-c64e9eac-aff8-4af7-bcd7-06dde3d99849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMTY3NjAsIm5iZiI6MTcxNTExNjQ2MCwicGF0aCI6Ii8xMTU4ODE2MzgvMjQ4NTUzMjg3LWM2NGU5ZWFjLWFmZjgtNGFmNy1iY2Q3LTA2ZGRlM2Q5OTg0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QyMTE0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjJhNjA5YzM1MWE5MzgzOWNmZTQxMmEzM2UwZTBjNjk0Y2Y3NDM1MGJmZjU2YjVjNDYxNDg5NmM3M2JjYzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zUVMEJHvMU_2ZAMxjV42LbsLS-KAmOE5kBvosWW0qvE) ![Screenshot_1](https://private-user-images.githubusercontent.com/115881638/248553288-57d21b5e-86de-4add-b802-05094f3efb04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMTY3NjAsIm5iZiI6MTcxNTExNjQ2MCwicGF0aCI6Ii8xMTU4ODE2MzgvMjQ4NTUzMjg4LTU3ZDIxYjVlLTg2ZGUtNGFkZC1iODAyLTA1MDk0ZjNlZmIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QyMTE0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWY3MTdhZjY4MWJiZTdkZTczOGViMjNkOTMyOWQ3ZTNlODhhMzhkYzY4NjUxYjE5ZDA3ZjVmMGFmNGQzYzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sVl1J2Cbpk5kOfwR-jAn5DkUAKhR7ZhNRueUajiHUXs)

Hallo,

leider habe ich genau das gleiche Problem.
Wenn ich in der Truhe bin und diese sortieren möchte mit Maus Mitteltaste, komme ich manchmal auf Shift+middle und dann sind meine Sachen einfach verschwunden. 
Ich hatte eine große Kiste (Diamant) inklusive Stack und es ist fast alles weg. Sehr ärgerlich, da ich viele seltene Dinge drin hatte. Wie kann ich das Problem beheben?
Ich würde mich sehr über eine Antwort freuen.

Liebe Grüße Yvonne
![Screenshot 2024-05-07 231907](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/169205302/f7aa2e8b-9b5d-4fa9-b531-467fa181c83b)

**Comment by Yveb** [comment]
so sah die Kiste danach aus. Fast alles weg.

**Comment by Yveb** [comment]
-Beim Rucksack ist mir das auch schon passiert-

**Comment by P3pp3rF1y** [comment]
@Yveb you're posting this in a closed issue and post this in English next time please. You will want to find the mod that you have in your pack that does sorting and disable it for sophisticated guis, can't help you more than that as it's the other mod that causes these issues
