### ISSUE TITLE
Dupe bug with two other mods - Request ability to ban inventory-having items from storage.

### ISSUE THREAD

**Issue by katubug** [P3pp3rF1y/SophisticatedStorage#212]
**Versions**:
Minecraft 1.19.2
Quark-3.4-405
Forge 43.2.11
Supplementaries 2.3.19
Sophisticated Core 0.5.73.333
Sophisticated Storage 0.8.30.482

Hi! Okay, so I'm having an obnoxious edge case in my modpack where Quark, Supplementaries, and Sophisticated Storage are creating an item dupe glitch.

**To reproduce**:
- In the Quark config, "Interpret Shulker-like blocks" is disabled. "Open Shulker Boxes" is true and so is "Enable Shulker Box Interaction." In the list of Shulker boxes, ONLY vanilla Shulkers are present.
- Upgrade a Sophisticated Barrel with a Stack Upgrade (I'm testing with tier 2).
- *In survival*, place down several Sacks and then break them. This enables the "shulker-like" ability.
- The sacks will have the easy-shulker interface where you can right-click items into them. Leave them empty for now.
- Place the sacks into the Sophisticated barrel, where they should stack due to the stack upgrade.
- Right-click items into the stack of Sacks.
- Split the stack of sacks with left or right click. Each sack retains the contents.

It's a little finicky but definitely reproducible. Nothing shows up in latest.log when this occurs, and neither I nor my other tester had a debug.log to check.

If it were up to me, I would ban Sacks from being placed into Sophisticated Storage, but alas that's not a feature Soph offers. I can't disable the crafting of Sacks because I have Integrated Dungeons and Structures, which places them in the world to find. Disabling the Stack Upgrades is defeating a lot of the purpose of having Sophisticated Storage in the first place. So my solution was to prevent shulker-like interactions on the Sacks, but that is apparently not working as intended.

Help would be greatly appreciated! I will be reporting this to all 3 mod authors.

Supplementaries: https://legacy.curseforge.com/minecraft/mc-mods/supplementaries/issues/775
Quark: https://github.com/VazkiiMods/Quark/issues/4252

**Comment by P3pp3rF1y** [comment]
Unfortunately these mods don't check stack size before running their stashing logic so they happily allow duping items like that in mods that allow stacking of items that normally have max stacksize 1. But there's a setting in config that allows setting these to not stack in sophisticated storages (and there's the same one in backpacks config) - `nonStackableItems`.

**Comment by MehVahdJukaar** [comment]
So I can fix this myself however I'd like to point out that by ignoring / bypassing the max stack size property you are entering in undocumented behaviour as you are expecting other mods items to work outside of the restraints they were built for which, unless of hacks, always holds. It's kind of like expecting some methods to accept null when it's marked as notnull
