### ISSUE TITLE
Snowman be able to put snow on a sophisticated barrel

### ISSUE THREAD

**Issue by MisterZam** [P3pp3rF1y/SophisticatedStorage#213]
I know this is oddly specific but I had to do it for the sake of automating snow blocks because apparently ender pearl is hard to get.. thank youu

**Comment by P3pp3rF1y** [comment]
No this is not possible, it would basically break the pickup upgrade or I would have to code it in less performant way. So I have to choose and will choose pickup being more performant and because of that snow won't be placed on top of these.
