### ISSUE TITLE
Feature/Bug - Quark chests

### ISSUE THREAD

**Issue by BloodshotPico** [P3pp3rF1y/SophisticatedStorage#22]
Seems like I'm unable to use this with Quark chests and I Like Wood chests, not sure if this is a bug or just not yet implemented.

So I'm unsure if this is a feature request or bug report. :)
Basically would like to be able to change the Quark mod chests and I Like Wood mod chests to that of Sophisticated storage if possible.

~Blood

**Comment by P3pp3rF1y** [comment]
latest version on curseforge has compat for Quark which allows them to be upgraded in world or changed in recipes
