### ISSUE TITLE
[1.19.2] Flat top barrel recipe crashes when using FastWorkbench

### ISSUE THREAD

**Issue by sigmastar00** [P3pp3rF1y/SophisticatedStorage#228]
Forge: 43.2.14
Fast Workbench: 7.1.3
Placebo: 7.2.0
Sophisticated Core: 1.19.2-0.5.77.346
Sophisticated Storage: 1.19.2-0.8.32.510

This recipe for toggling between the flat top barrel model causes a client crash if you attempt to convert more than one barrel at a time by shift clicking the output. This crash only occurs when FastWorkbench is installed.

Crash report: https://hastebin.com/share/fuxihasivi.php

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
