### ISSUE TITLE
[1.20.1] [Bug] The name of barrels will display wrongly when with Jade

### ISSUE THREAD

**Issue by Cactusstudent** [P3pp3rF1y/SophisticatedStorage#229]
Minecraft Version: `1.20.1`

Forge Version: `47.0.35`

Mod List: `Jade`, `JEI`, `Sophisticated Storage`, `Sophisticated Core`, `Catalogue`.

Description: When you create a new world with mods above, and move your mouse pointer until you point the Barrles like this. And then it will display the `%s` (normally it will be the material of this barrle), it only happens on the block state of the barrles.

Other information: **Have told this bug to Jade's Author**. 

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/97865546/5e90d7b6-125b-4a73-85f5-0d098a3bec0b)

**Comment by P3pp3rF1y** [comment]
Which vesion of storage is that? I am pretty sure I fixed this bug so please make sure you're testing with latest

**Comment by Cactusstudent** [comment]
Test it with Sophisticated Storage 1.20.1-0.8.35.507.

**Comment by P3pp3rF1y** [comment]
Had to add jade compat afterall so that it would use the method correct for these storages

**Comment by P3pp3rF1y** [comment]
included in the latest release on CF
