### ISSUE TITLE
Item voiding bug with chests & stack upgrade

### ISSUE THREAD

**Issue by HappyCerberus** [P3pp3rF1y/SophisticatedStorage#23]
Sorting a chest with the stack upgrade lead to the chest voiding all crafted items.

This was a block chest, so things like cut blocks or bricks got voided.

Core: 1.18.2-0.1.0.19, Storage: 1.18.2-0.0.16.30 (Direwolf pack)

**Comment by P3pp3rF1y** [comment]
As commented separately this is caused by InventorySorter and setting the sort key for both storage and backpacks to the same one that InventorySorter will solve this issue for you, which is the only solution until InventorySorter fixes its compatibility implementation and config blacklist.
