### ISSUE TITLE
Packing tape prevents barrels from being seen by Storage Controller

### ISSUE THREAD

**Issue by Arialla-Fio** [P3pp3rF1y/SophisticatedStorage#230]
Problem: Sophisticated Storage Controller + Ars Storage Lectern for remote access failed to pick up barrels I added after moving them with packing tape.

Testing: I tried several different approaches thinking maybe it was an issue of not enough Bookwyrms, or something, but was able to determine that I had set up the Storage Lectern correctly, and that the Storage Controller wasn't picking those barrels and their contents up.

Solution: Break all of those barrels, and re-add them to the network without using packing tape, and return all items to barrels. Now they show up just fine.

This issue was noticed in the Cottage Witch Recast modpack.

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest version on CF
