### ISSUE TITLE
Quark filter buttons support

### ISSUE THREAD

**Issue by khazenor** [P3pp3rF1y/SophisticatedStorage#24]
Would it be possible to support the inventory buttons from quark?  Their ability to dump all items already in the chest in the chest is very helpful.  No worries if this is too much work.  Just a feature that I really enjoy using when I play on my own.

![image](https://user-images.githubusercontent.com/80185732/172023488-ccf08bfe-ce66-4958-9653-998e92091911.png)

**Comment by P3pp3rF1y** [comment]
the buttons are added in the latest version of sophisticatedcore on curseforge
