### ISSUE TITLE
Incompatibility with JEI 

### ISSUE THREAD

**Issue by SrRapero720** [P3pp3rF1y/SophisticatedStorage#248]
### ISSUE (sophisticated storage)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/56f45632-9c90-44a9-90f4-627bd2f60203)

### EXPECTED (sophisticated backpacks)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/de0df0f0-98fd-4ad1-8bdf-95037343a39d)

**Comment by P3pp3rF1y** [comment]
What versions of the mods are you using? any error related to sophisticated storage in the log? 

This works correctly for most of the people including me and I find it odd that this wouldn't work for storage only because most of the logic is actually common to both of the mods and is done as part of sophisticatedcore. The only thing that storage does on top of that is just registering that logic to jei for its gui.
So I am suspecting that some mod is messing with storage and breaking this compat.

**Comment by SrRapero720** [comment]
My bad i forgot to mention version
I am using 1.18.2 with MinecraftForge 40.2.9

SCore: sophisticatedcore-1.18.2-0.5.77.360.jar
SStorage: sophisticatedstorage-1.18.2-0.8.37.554.jar
SBackpacks: sophisticatedbackpacks-1.18.2-3.18.57.888.jar

Modpack: https://legacy.curseforge.com/minecraft/modpacks/marillanos/files

I found JEI is not working at all with SStorage
For example

## Items CAN'T be moved using JEI button (when crafting upgrade is present)
**STORAGE**
![2023-07-16_22h16_47](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/1e734176-2ccb-4a99-8111-c21a1bb248c9)
![2023-07-16_22h16_55](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/af4758bd-0270-42a3-8f84-6e626f52692d)

**BACKPACKS**
![2023-07-16_22h17_05](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/c5f62f40-e6ba-47a2-8c03-1e249f0c8d8e)


## MISSING BARRELS REPICE
**Using JEI can't get repice for crafting chest or barrels using crafting table EXCEPT with Create Mod**
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/28f76a96-eb75-4362-805b-8a1898736d9e)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/41307e3c-6b2e-4604-b99d-0fcccfc176cb)

**Comment by SrRapero720** [comment]
note: repices are working (in crafting table) but JEI can't identify it

**Comment by P3pp3rF1y** [comment]
that basically means that the whole JEI integration didn't load. Anything in the log when JEI registers plugins? there should be something like `Registering advanced plugins: sophisticatedstorage` in the log or similar message for sophisticatedbackpacks or another mod and if there's issue with loading sophisticatedstorage plugin there should be error logged there.

**Comment by SrRapero720** [comment]
you're right
```

[17:26:37] [Render thread/INFO] [me.je.co.lo.PluginCaller/]: Registering recipes: sophisticatedstorage:default ...
17:26:37.554
game
[17:26:37] [Render thread/ERROR] [me.je.co.lo.PluginCaller/]: Caught an error from mod plugin: class net.p3pp3rf1y.sophisticatedstorage.compat.jei.StoragePlugin sophisticatedstorage:default
17:26:37.554
game
at net.p3pp3rf1y.sophisticatedstorage.compat.jei.TierUpgradeRecipesMaker.lambda$getCraftingRecipes$0(TierUpgradeRecipesMaker.java:44) ~[sophisticatedstorage-1.18.2-0.8.37.554.jar%23205!/:1.18.2-0.8.37.554] {re:classloading}
17:26:37.554
game
at net.p3pp3rf1y.sophisticatedstorage.compat.jei.TierUpgradeRecipesMaker.lambda$getCraftingRecipes$1(TierUpgradeRecipesMaker.java:31) ~[sophisticatedstorage-1.18.2-0.8.37.554.jar%23205!/:1.18.2-0.8.37.554] {re:classloading}
17:26:37.554
game
at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.lambda$getAndTransformAvailableItemGroupRecipes$2(ClientRecipeHelper.java:42) ~[sophisticatedcore-1.18.2-0.5.77.360.jar%23204!/:1.18.2-0.5.77.360] {re:classloading}
17:26:37.554
game
at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.lambda$getAndTransformAvailableItemGroupRecipes$3(ClientRecipeHelper.java:40) ~[sophisticatedcore-1.18.2-0.5.77.360.jar%23204!/:1.18.2-0.5.77.360] {re:classloading}
17:26:37.554
game
at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.getAndTransformAvailableItemGroupRecipes(ClientRecipeHelper.java:40) ~[sophisticatedcore-1.18.2-0.5.77.360.jar%23204!/:1.18.2-0.5.77.360] {re:classloading}
17:26:37.554
game
at net.p3pp3rf1y.sophisticatedstorage.compat.jei.TierUpgradeRecipesMaker.getCraftingRecipes(TierUpgradeRecipesMaker.java:29) ~[sophisticatedstorage-1.18.2-0.8.37.554.jar%23205!/:1.18.2-0.8.37.554] {re:classloading}
17:26:37.554
game
at net.p3pp3rf1y.sophisticatedstorage.compat.jei.StoragePlugin.registerRecipes(StoragePlugin.java:149) ~[sophisticatedstorage-1.18.2-0.8.37.554.jar%23205!/:1.18.2-0.8.37.554] {re:classloading}
```

**Comment by P3pp3rF1y** [comment]
ok so from that I can see there was an error loading that, but I don't see what error so I can't help without more info. Could you share the full log on something like pastebin.com?

**Comment by SrRapero720** [comment]
sorry for the late response
here is both (latest and debug.log)
https://gist.github.com/SrRapero720/fb9a3dfbde175e9601195ab5df685516

**Comment by P3pp3rF1y** [comment]
Looks like for some reason at least one of the tier upgrade recipes is invalid and that causes the logic that adds these in JEI to fail. Are you or the pack maker changing these in any way?

**Comment by SrRapero720** [comment]
ehhh nope, i am the creator of the modpack and i didn't make changes to config of the mod. 
(even the mod itself)

**Comment by SrRapero720** [comment]
i figure out what is happen
MCA is the mod causing the bug
removing it fixes the issue

**Comment by SrRapero720** [comment]
## WITH MCA
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/379d4d7d-c964-4c31-9fcd-4448f763b3b1)

## WITHOUT MCA
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/5deac1ca-c3c7-4f9f-91ba-2a547b330b03)
![2023-07-26_17h16_55](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/915ee7e4-8903-47df-99f1-6aae6ffc9e60)

**Comment by MuteTiefling** [comment]
We're seeing the same thing in Enigmatica 9. https://github.com/EnigmaticaModpacks/Enigmatica9/issues/546

The normal mode does not change any recipes and we're seeing it there as well. 

The + appears in backpacks with the crafting upgrade, but not in barrels with the upgrade. 

We don't have MCA, so that's out, but I wouldn't fully discount a mod conflict somewhere. 

MC: 1.19.2
JEI: jei-1.19.2-forge-11.6.0.1016
Sophisticated
Core: sophisticatedcore-1.19.2-0.5.82.382
Storage: sophisticatedstorage-1.19.2-0.8.38.555
Backpacks: sophisticatedbackpacks-1.19.2-3.18.55.889
Logs: https://gist.github.com/MuteTiefling/fc87361a238167d7542739d41d46deeb

**Comment by SrRapero720** [comment]
New update fixes the issue, now with MCA works fine. move to crafting table works and gui interface moves when upgrade menu is opened

![2023-08-09_01h16_40](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/666ad0ae-b879-4d6a-961f-efef4c1de260)
![2023-08-09_01h17_17](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/c4e5d800-79c5-42ed-b5cb-a936b02a30d2)
![2023-08-09_01h17_41](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29090346/e6a3ead6-0376-494c-9246-1ff1863d481c)
