### ISSUE TITLE
Putting Botany Hopper Pots on top of Netherite Chests cause huge lag when the chests fill up.

### ISSUE THREAD

**Issue by borsvadim** [P3pp3rF1y/SophisticatedStorage#249]
I first reported the issue to the dev of Botany Pots - and he had already run tests on this issue. It works perfectly fine with Vanilla Chests. So I'm guessing it's something about the way Sophisticated Storage deals with these bots once the chest is full?

Spark Profiler link: https://spark.lucko.me/VlWLEHSpes

![253762937-18908bdb-6cea-455d-9e8c-faab06b8e8c4](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/394459/16555f11-b145-4be6-8ab3-6b37a32bdd13)

**Comment by P3pp3rF1y** [comment]
can you retry with latest version? I changed that part of the code and released new version more than a month ago.

**Comment by borsvadim** [comment]
What version would that change be in? I am currently playing ATM8 in 19.2. I can install a different version if you need someone else to test it, just let me know what version to use.

**Comment by P3pp3rF1y** [comment]
I mean you can still update to the latest version of the mods without the need to update the pack itself, but looks like the latest version of that pack should have updated sophisticated mods with the fix

**Comment by P3pp3rF1y** [comment]
closing
