### ISSUE TITLE
[1.18.2] Client crash when breaking Gold upgraded barrels

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/SophisticatedStorage#25]
https://gist.github.com/ProsperCraft/91608107e103ba85dc9f5de05dadde71

It looks to be something related to twilight forest.

breaking in creative causes the client crash as well.
https://gist.github.com/ProsperCraft/f42f672221e9f27ee619cef6225a9e21

**Comment by ProsperCraft** [comment]
Gold chests do not crash.

**Comment by P3pp3rF1y** [comment]
I have this fixed in dev, but try to set display item to something like one of the spawn eggs on chest, I have a suspicion that's going to crash with TF as well and there's nothing I can do there

**Comment by rHytopia** [comment]
I have this Crashlog: https://bytebin.lucko.me/43MDXee26l

**Comment by Sonic1305** [comment]
We also have had this issue happening but the chunk in which the crash has occured is now invisible when using Rubidium (& Oculus). I just don't know how to get my chunk back to load as even a server restart still makes the chunk invisible (still walkable and visible to other players)

**Comment by P3pp3rF1y** [comment]
Latest version on curserforge has the fix for this.
