### ISSUE TITLE
1.19.2 Sophisticated Storage Crash with Optifine

### ISSUE THREAD

**Issue by 74153** [P3pp3rF1y/SophisticatedStorage#250]
Game has been crashing with OptiFine on when I click on the storage setting to "choose Item in storage to display" then game freezes for a split second and proceeds to crash. When I re attempt to join the world (Single player/ Multiplayer), game still crashes before joining because OptiFine is activated.

**Comment by 74153** [comment]
So I found a solution, I tried different versions of OptiFine.
The one I had installed was OptiFine_1.19.2_HD_U_H9.

I removed it and installed the OptiFine_1.19.2_HD_U_I1 version.

So now when I select which Item from the storage I want to display, it doesn't lag nor it crashes.

**Comment by P3pp3rF1y** [comment]
Sure, because that previouis version is incompatible with forge for 1.19 and crashes like you experienced.
