### ISSUE TITLE
Compression upgrade missing step

### ISSUE THREAD

**Issue by jeytee84** [P3pp3rF1y/SophisticatedStorage#254]
Building a compressor chest in AOF8, somehow the upgrade misses the recipe for **1x compressed deepslate to deepslate**.
Not that big of a deal but probably not expected behaviour and it might be happening to other blocks as well so I thought it worth mentioning.

https://imgur.com/a/Py034Cz

Love the mod, really sophisticated, thanks for all your hard work guys.

**Comment by P3pp3rF1y** [comment]
I don't know what AOF8 is, but this would happen if there was some issue with recipes - when you compress deepslate using 3x3 recipe is the compressed one the only thing that comes up in JEI or there are multiple results for that recipe? And the same for uncompressing is there perhaps another variant of deep slate the compressed one can be uncompressed into?

**Comment by P3pp3rF1y** [comment]
Closing this as I didn't get more info but at the same time I am shortly releasing a small change that handles conflicting compacting / uncompacting recipes so that may potentially fix the issue here as well.

**Comment by v3ctordesign** [comment]
Oh, I'm sorry for missing that reply, AOF8 would be the modpack All of Fabric 8, but since that doesn't exist, I just realized it was a typo, i meant ATM8 as in All the Mods 8.

**Comment by jeytee84** [comment]
Oh, I'm sorry for missing that reply, AOF8 would be the modpack All of Fabric 8, but since that doesn't exist, I just realized it was a typo, i meant ATM8 as in All the Mods 8.
