### ISSUE TITLE
Suggestion: Advanced compression upgrade

### ISSUE THREAD

**Issue by jeytee84** [P3pp3rF1y/SophisticatedStorage#255]
The current compression upgrade has 5 steps.
An advanced version could be 7-8 or even 10 (or could be tiered like stack upgrades).

**Comment by P3pp3rF1y** [comment]
I feel like that would be way too op and there's already a config you can use to set compression upgrade to compress more slots so you can change that in your world / pack `maxNumberOfSlots` in compression upgrade config section
