### ISSUE TITLE
hopper upgrade will not push or pull from composter

### ISSUE THREAD

**Issue by kippyayo** [P3pp3rF1y/SophisticatedStorage#263]
pretty much exactly as the title says, i dont know if its something purposefully not included in the mod. im just trying to make a more compact simple bonemeal machine in my farming area, but the hopper upgrade will not push or pull either items to be composted or bonemeal from the composter.

**Comment by P3pp3rF1y** [comment]
is the storage that's pushing into the composter above it and the one that is pulling from it below?

**Comment by kippyayo** [comment]
yep, thats correct! ive also tried with the advanced hopped and messing around with the settings a bit, including having one pull and push, with no results.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version just released on curseforge
