### ISSUE TITLE
Storage Controller distributed item randomly

### ISSUE THREAD

**Issue by Yamadaisme** [P3pp3rF1y/SophisticatedStorage#265]
When I update the mod, item input from hopper to Storage Controller distribute ramdomly into chest without filling up the others first.

**Comment by P3pp3rF1y** [comment]
what does it mean randomly - is it filling random slots in an empty chest instead of filling chest which already has that item? 
Is it filling the closest chest instead of the one that has the item?
Can you provide steps on how I can recreate this?

**Comment by Yamadaisme** [comment]
So I link a row of barrels from bottom to top to a Storage Controller, then I put a hopper on top of the Controller and put item in it. Instead of filling from bottom chest, it fill up from middle chest (usually third or fourth one in the row). By the way, I just reverted the mod and it work normal

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version of sophisticated core just released on curseforge
