### ISSUE TITLE
Crash with Rubidium [1.20.1 - Forge 47.1.43]

### ISSUE THREAD

**Issue by RawlethS** [P3pp3rF1y/SophisticatedStorage#266]
Crash on boot up.

MC Version: 1.20.1
Forge Version: 47.1.43 (also crashed on 47.1.1 and 47.1.3)

Mod list:
Rubidium 1.20.1-0.7.0a
Sophisticated Core 1.20.1-0.5.83.395
Sophisticated Storage 1.20.1-0.8.44.571

Log:
https://mclo.gs/fTOVO2q

**Comment by P3pp3rF1y** [comment]
fixed in the latest version on CF
