### ISSUE TITLE
All Netherite Limited Barrels have a consistent visual bug.

### ISSUE THREAD

**Issue by 5PIterator** [P3pp3rF1y/SophisticatedStorage#270]
![2023-08-09_08 45 33](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/117373175/32e24419-69e2-4035-9800-aadfb712a73f)
![2023-08-09_08 45 17](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/117373175/83beace2-15f9-4c19-b42a-123ab4d4b671)
Fully upgraded Limited Barels have a bug where the toggle for their upgrades. 

Version used v1.18.2-0.8.38.572.

**Comment by P3pp3rF1y** [comment]
Latest version of sophisticated core has refactored the upgrade gui and it also fixed this issue
