### ISSUE TITLE
Client crash when shift clicking storage upgrades

### ISSUE THREAD

**Issue by loving2** [P3pp3rF1y/SophisticatedStorage#271]
Sophisticated Storage Version
sophisticatedbackpacks-1.20.1-3.18.56.890
sophisticatedcore-1.20.1-0.5.83.395
sophisticatedstorage-1.20.1-0.8.46.579

Environment
Dedicated Server

Cross-Mod Interaction
Yes

Expected Behavior
Shift clicking storage upgrades should move the stack into the inventory

Actual Behavior
Game crashes to desktop and continues crashing to desktop every time you load back in

Steps to Reproduce
1) Autocraft several diamond stack upgrades in AE2
2) Shift click them out of AE2

Additional Information
This crash can probably be reproduced in other ways, the above is just what I was doing when it happened. I use Sophisticated Storage as my storage in AE2, if that matters. Crash log linked here https://mclo.gs/3GwAwl2

**Comment by P3pp3rF1y** [comment]
That's Rubidium crashing you, update to 0.7.0+ or downgrade storage as this latest version of storage is only usable with that version of Rubidium
