### ISSUE TITLE
Sophisticated shulker box deletes items

### ISSUE THREAD

**Issue by ivanirucho** [P3pp3rF1y/SophisticatedStorage#272]
When you hold a shulker box and right-click an item to store it inside, the box will accept items even when it's already full and removes them.

**Comment by P3pp3rF1y** [comment]
You probably have quark in the pack and have it set to allow stashing items in shulker box like items. That then saves the data in different place than sophisticated storage stores its data. Just disable that quark feature and your issue will be fixed

**Comment by ivanirucho** [comment]
thanks it was
