### ISSUE TITLE
Crashed when the Stack upgrade for sophisticated chests are in your inventory

### ISSUE THREAD

**Issue by ItzDingus** [P3pp3rF1y/SophisticatedStorage#273]
[crash-2023-08-12_01.36.35-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/12326729/crash-2023-08-12_01.36.35-client.txt)
Here is a crash log, seems like it just gets a generic error and closes out my GD launcher instance when I had the stack upgrade in my inventory. I had to use NBTExplorer to remove the stack upgrade from my inventory. not sure if its even your mod, or somehting i have conflicting, would just like your insight!

i crafted the stack upgrade 1

**Comment by P3pp3rF1y** [comment]
That version of storage is compatible with Rubidium 0.7.0 + so either update to that or downgrade storage to previous version
