### ISSUE TITLE
Sophisticated Storage crashing when putting tier 4 stack upgrade into inventory

### ISSUE THREAD

**Issue by pestulance** [P3pp3rF1y/SophisticatedStorage#274]
Version 1.20.1-0.8.46.579

Game crashes out on SSP and MP when putting the stack upgrade in inventory. first noticed on server then was able to instantly replicate the crash on ssp on a fresh created world.

[crash report.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/12330500/crash.report.txt)

**Comment by P3pp3rF1y** [comment]
That version of storage is only compatible with Rubidium 0.7.0 + Either update to that version or downgrade storage to previous

**Comment by P3pp3rF1y** [comment]
closing this

**Comment by Proxwian** [comment]
What version of storage should I downgrade? Latest Rubidium is bugged as duck

**Comment by P3pp3rF1y** [comment]
just the last version is made for Rubidium 0.7.0 the previous one is for previous versions of Rubidium
