### ISSUE TITLE
UI Elements Not Always Rendering When Viewing Storage UI

### ISSUE THREAD

**Issue by Darkosto** [P3pp3rF1y/SophisticatedStorage#277]
Hello!

When opening a Sophisticated Storage GUI, certain UI elements do not always render such as Item Borders: 
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/10309699/ad07f560-bcaa-405a-a180-8413d225d306)

vs. 

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/10309699/1a0fd6e6-de71-46b2-93af-fab75e45913f)

I checked other items and blocks but did not see issues outside of this one mod interaction

Thank you!
Darkosto

MC: 1.20.1
Forge: 47.1.44
Sophisticated Storage: 0.8.46.579
Sophisticated Core: 0.5.83.395
Item Borders: 1.2.0

**Comment by P3pp3rF1y** [comment]
The latest version of sophisticated core on CF has compatibility for item borders to render them in sophisticated inventories in general.
