### ISSUE TITLE
Game crash after pulling out certain items

### ISSUE THREAD

**Issue by Maauriice** [P3pp3rF1y/SophisticatedStorage#278]
The game crashes after : 
- having a chest placed and pulling out a stacking upgrade
- having storage controller placed and pulling out storage tool

Crash report:
https://mclo.gs/wu5lZKw#L299

Is an interaction with another mod at fault? Im on the "new game" 1.20.1 modpack.

**Comment by P3pp3rF1y** [comment]
You have incorrect version of Rubidium, either update to 0.7.0 which the latest version of storage is compatbile with or downgrade to previous version of sophisticated storage which is compatible with Rubidium 0.6.5

**Comment by Maauriice** [comment]
Thank you!

**Comment by P3pp3rF1y** [comment]
btw latest version is coded in a way where it's compatible with both versions of Rubidium so you shouldn't crash with that regardless of Rubidium being 0.6.5 or 0.7.0
