### ISSUE TITLE
BUG - ctrl+middle mouse click 

### ISSUE THREAD

**Issue by 0bstidian** [P3pp3rF1y/SophisticatedStorage#289]
Hi, not sure if anyone reported this before but using the mod below with sophisticated storage and backpacks can delete the items inside the chest. You can recreate the bug by filling the chest with stack upgrades, going over the limit of a full chcest without the upgrades and then using CTRL + middle mouse click.

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/38041508/f3ec5595-2814-4415-8168-c9db8d249064)

**Comment by P3pp3rF1y** [comment]
yup that was reported but it needs to be solved on inventory sorter side of things including the bug in inventory sorter where guis cannot be marked as not to work with it even though it actually has that functionality but is just broken for a while now. 
From looking at Inventory sorter issues it appears this was actually fixed for 1.18.2 but the fix wasn't merged forward into newer versions. Anyway as said this needs to be fixed on that side so feel free to follow up in one of the tickets over there.
