### ISSUE TITLE
Storage Controller Issue

### ISSUE THREAD

**Issue by Puffle2K** [P3pp3rF1y/SophisticatedStorage#290]
I am trying to use the storage controller combined with a lot of storages to do inventory sorting. I have filters in many of my storages, but I also need to have extra storage that can store items not filtered. When putting items into the storage controller, they seem to prioritize the nearest available storage instead of the storage that has a filter for that item. Is there a way to fix this without putting my unfiltered storage further away?

**Comment by Puffle2K** [comment]
Edit: It seems as though it will prioritize a storage with the same item already in it. However, I would like to be able to set filters up before I get an item and have the storage still sort it. For example: having a chest for a specific mod and having all the new stuff I get for that mod automatically sorted.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
