### ISSUE TITLE
Barrels cant be utilised by Villages for Fisherman POI

### ISSUE THREAD

**Issue by xanthian** [P3pp3rF1y/SophisticatedStorage#292]
Would be a nice to have at least if just for the vanilla barrel styles.

**Comment by P3pp3rF1y** [comment]
Actually thought about this for a bit, but I am not going to add this functionality. First of all it doesn't seem super easy to add blocks to existing POI types and second I don't like the idea of not being able to use barrels in villages apart from when I intentionally want to have a fisher villager.
