### ISSUE TITLE
Chest JEI overlay

### ISSUE THREAD

**Issue by TheOGWeston** [P3pp3rF1y/SophisticatedStorage#294]
The JEI item info is showing behind the items only in sophisticated storage chests
![Screenshot 2023-10-05 153421](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/75309095/0ad1ec89-2d60-43d4-a178-bbf03c052a38)
![Screenshot 2023-10-05 153511](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/75309095/5e454073-e49f-470e-8905-2681611e98ac)

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
