### ISSUE TITLE
[Suggestion] Add config to hide most variants in JEI

### ISSUE THREAD

**Issue by Le6barbare** [P3pp3rF1y/SophisticatedStorage#295]
Hello !

This request is similar to Suggestion #66 but with a larger scope :
A config option to hide most of the many variants of the barrels and chest, leaving only one row for each wood/colored variants, and only oak iron/gold/diamond/netherite versions for each barrel type/chest block

This option will be disabled by default, but for those like myself who like a streamlined JEI list, I sincerely thinks it'll be a great addition to the mod

Thanks!

**Comment by P3pp3rF1y** [comment]
There are now these two configs `showHigherTierTintedVariants` and `showSingleWoodVariantOnly`. It's not exactly what's asked for here, but it's achieving the goal of showing way less in JEI so I am closing this as complete
