### ISSUE TITLE
The game crashed, when I opened the world all the items in my backpacks were removed (even items from backpacks that I had stored in chests).

### ISSUE THREAD

**Issue by 1t5Amaya** [P3pp3rF1y/SophisticatedStorage#299]
![imagen_2023-10-30_140402426](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/149432013/b5ccb77a-84e9-4671-b394-626e8131ea67)

**Comment by P3pp3rF1y** [comment]
That means the server crashed in the way where it didn't save the data. There's nothing I can do about that other than recommending that you use a backup mod if you want to have a way of getting the contents back.
