### ISSUE TITLE
Limited Barrels with Void Upgrades not voiding after chunk unloads and then reloads.

### ISSUE THREAD

**Issue by NullMagic** [P3pp3rF1y/SophisticatedStorage#300]
Basically, if you have a limited barrel with a void upgrade in it and you leave the chunks it's in and then come back, the void upgrade stops working until you manually remove items from the barrel and then add them back.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this. will need more details on what kind of setup you're using and how I can recreate. Also make sure that you are on the latest version of the mod in the given version of MC.

**Comment by P3pp3rF1y** [comment]
closing given no response
