### ISSUE TITLE
Suggestion: Modify the sort options (applies to Sophisticated Backpacks as well)

### ISSUE THREAD

**Issue by taj1994** [P3pp3rF1y/SophisticatedStorage#304]
I've been wondering for a while now why the sorting was weird in both Sophisticated Storage chests, and in Sophisticated Backpacks:

The default sort option with the top-right button is "By Name", but the items weren't in alphabetical order

Tonight, I just figured it out. I noticed that it's sorting by *mod* name, not _item_ name

---

So, my suggestion is a few options:

1. Modify the button to say "By Mod" or "By Mod Name" instead of "By Name"
2. Change it to sort by item name instead of by mod
3. Add an option that sorts by item name alongside the current options. This would still require option 1, then the "By Name" label would sort by item name instead of by mod name (either keep the "By Name" label and use it for this, or call it "By Item Name")

Option 3 would probably be the ideal option (it would keep the current sorting option for people that prefer that, but also give the "sort items alphabetically" option that others (like myself) would prefer), while option 1 would likely be the easiest to implement, and make the sorting method more clear without needing to change anything significant

**Comment by P3pp3rF1y** [comment]
Some time ago I added sorting by actual item name (instead of its registry name) and sorting by mod uses mod name first and then item name so this is included in the mods
