### ISSUE TITLE
Suggestion: Add Compat with Cloud Storage

### ISSUE THREAD

**Issue by GentlemanCheesy** [P3pp3rF1y/SophisticatedStorage#305]
Cloud Storage adds a really creative take on modular storage that I use quite often, unfortunately Cloud Storage doesn't allow for Sophisticated Storages to be attached with Balloons and added to a Cloud Chest. 

I'd really appreciate some sort of addition that allows for your storages to be used. Cloud Storage allows for most other mod's chests to be used. Here is their GitHub!

https://github.com/AlexModGuy/CloudStorage

**Comment by P3pp3rF1y** [comment]
From the first look it seems you need to ask them to add compat because it looks like they only take number of slots from the given storage and add that to a huge cloud chest. Have you tried speaking to them about adding compat with modded storages in general?

**Comment by GentlemanCheesy** [comment]
I haven't had issues with other storage mods so far which is why I opened an issue here first. I'll gladly open an issue over on their github though, I guess I hadn't thought about cloud storage adding some sort of fix for this instead.

Probably would make more sense for them to add some sort of option to add extra storage blocks to the mod, maybe via a config or datapacks.

**Comment by P3pp3rF1y** [comment]
closing as this one is clearly for cloud storage to add support for modded inventories if they intend to have that compat
