### ISSUE TITLE
[Feature Request] Show Total Storage Capacity for Limited Barrels

### ISSUE THREAD

**Issue by Darkosto** [P3pp3rF1y/SophisticatedStorage#309]
Hey P3pp3rf1y!

I don't believe this is currently a feature in Sophisticated Storage, but is there an option to make the total amount of storage visible when using Limited Barrels? After making upgrades and setting up a storage system, it's tough to know how much can fit into my barrels.

Thanks for all of your hard work!
Darkosto

MC: 1.20.1
NeoForge: 47.1.79
Sophisticated Storage: 0.8.61.605
Sophisticated Core: 0.5.89.425

**Comment by P3pp3rF1y** [comment]
Just released new version and there are now a few ways
- tooltip of the item in storage shows total capacity wheneve that slot can go over item's max stack size (so it will always display for limited barrels)
- limited barrels gui got an update and as part of that you can now see bars showing capacity taken visually as well as percentage value
- similar bars will show in world when storage tool or tier upgrade is held and their display can be toggled to show permanently
