### ISSUE TITLE
Spelunkery Compat for Compression

### ISSUE THREAD

**Issue by Dragnier** [P3pp3rF1y/SophisticatedStorage#311]
When [Spelunkery](https://www.curseforge.com/minecraft/mc-mods/spelunkery) is added alongside your mod, the compression upgrades stop working on raw gold, raw iron, coal, redstone, lapis, and possibly other things like diamonds and emeralds though I didn't check those. I know Spelunkery adds raw nuggets and shards for each of these items so it is probably related to that somehow.

**Comment by P3pp3rF1y** [comment]
I made a change to how compacting recipes are queried so another mod adding it's own version of 2x2 or 3x3 recipe should no longer affect vanilla or other recipes and it's now really down to just recipes existing that allow compacting / uncompacting of items/blocks. If you happen to run into this again please open a new issue for that.
