### ISSUE TITLE
Issue using IntegratedTerminals

### ISSUE THREAD

**Issue by RevBeast** [P3pp3rF1y/SophisticatedStorage#316]
Description:
Storage terminal (from integrated terminals mod) does not view the items inside of sophisticated storage chests/barrels (found testing these two mods alone). 

Steps to reproduce: get a chest/barrel (warped barrel and a diamond chest were used by me), put items in it, attach an item interface to it and link that to a storage terminal with a logic cable. The storage terminal will work fine and show the items of the inventory. Break the inventory and place it back again in the same spot and put items inside. The storage terminal will not show the items inside the chest anymore (even if the terminal/cable/interface were broken and placed back again).

I reported this issue to the IntegratedTerminals mod dev and they suggested I report here because you might have "some issues with Sophisticated storage's item handler capability implementation". Link: https://github.com/CyclopsMC/IntegratedTerminals/issues/115.

**Comment by P3pp3rF1y** [comment]
I have posted more info on integrated terminals tracker but this really needs to be fixed on Integrated Terminals side of things. I tried to "fix" it on my side by working around the predicament of only setting the block as changed once and my code was getting very bloated to the point it was getting difficult to understand when a change would be saved.
