### ISSUE TITLE
Upgrade Tabs are interfered with by JEI

### ISSUE THREAD

**Issue by CharitableClas** [P3pp3rF1y/SophisticatedStorage#32]
tab doesnt hide JEI so when you try to click on the button it click the item in JEI behind it
![unknown](https://user-images.githubusercontent.com/34020766/175193390-7b797df9-4334-4144-b236-9db4ba81951f.png)

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this one in dev or in ATM7 modpack so I will need more info on how to recreate / info on whether you get this behavior with just storage and jei or what minimum set of mods is needed to recreate it

**Comment by CharitableClas** [comment]
I have GUI scale 3 as I have bad eyesight even with glasses. Therefore its hard for me to see small items so thats probably it also I can probably change some settings for JEI that might help.

**Comment by P3pp3rF1y** [comment]
Closing - discussed separately that this was caused by a bug in JEI that is fixed in latest version.
