### ISSUE TITLE
Sophisticated Chests/Barrel with Hopper upgrade ejects to the left instead of down.

### ISSUE THREAD

**Issue by Euchale** [P3pp3rF1y/SophisticatedStorage#322]
I don´t know how I caused it, but my Sophisticated barrels now output to the left instead of of down. This applies to both barrels and chests, and affects all of my newly placed ones. The ones I had previously placed are not affected. 

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/3716287/1a81b7f9-7b89-4c71-947f-e18cfea89e89)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/3716287/9cf2fc74-34fd-4fb0-86f4-49883cd4fda7)

Logging out and back in did not fix it. Breaking Barrel and replacing did not fix it. 
Let me know of any logs or whatever might be useful to figure out this bug has happened.

Additional Info: I'm in the AllTheMods9 Modpack.

**Comment by P3pp3rF1y** [comment]
They output to the bottom of the barrel, but because barrel can placed in different rotations bottom in your case is to the left. if you place barrels with front not facing up or down but rather to one of the N/S/W/E the bottom will be down and they will output to the block below them

**Comment by Euchale** [comment]
If you check out the screenshots it was the chest doing it however. And I tried several rotations as I was thinking this might be the case.

**Comment by P3pp3rF1y** [comment]
Ok in that case I will need steps to recreate as I am unable to recreate by simply placing chest in any of the rotations and placing the hopper upgrade in. Have you perhaps moved that upgrade between barrel an chest?

**Comment by Euchale** [comment]
Ok did some testing to see if I can reproduce it fully, here are the steps:

Insert Hopper Upgrade into Barrel.
Break Barrel.
Insert Upgrade into either Barrel/Chest
It now inserts to the left instead of down.

**Comment by P3pp3rF1y** [comment]
This was fixed in sophisticated storage release a bit ago
