### ISSUE TITLE
Suggestion: Reset look

### ISSUE THREAD

**Issue by Hirsu** [P3pp3rF1y/SophisticatedStorage#323]
Hi,

I've been looking for a way to reset a barrel's look after it's been dyed. I've tried the obvious tricks, like putting it in a crafting table or right clicking it when held in hand. As none of these worked and because this feature isn't mentioned on the curseforge page, I'm led to believe this feature doesn't exist yet.

I like to try out several looks for barrels before I craft a bunch of them, but this means I need to use a new one for every different look. It would be nice if we could reset the look to default, so we could redye the barrel from scratch.

Would it be possible to create this feature, please?

Thanks!

**Comment by P3pp3rF1y** [comment]
you can just put it in cauldron filled with water and wash the color away that feature is already there

**Comment by Hirsu** [comment]
> you can just put it in cauldron filled with water and wash the color away that feature is already there

Perfect, thank you!
I didn't find the feature on the curseforge page and I hadn't thought of that.
