### ISSUE TITLE
Resource pack causing texture issues / textures are too big on limited barrels.

### ISSUE THREAD

**Issue by cptretro** [P3pp3rF1y/SophisticatedStorage#332]
I'm using the faithless pack https://www.curseforge.com/minecraft/texture-packs/faithless 

is there any fix for this like pointing the mod to the vanilla textures or resizing those icons. I love this mod and I love the faithless resource pack and I would love to use them together.

<img width="808" alt="image" src="https://github.com/P3pp3rF1y/SophisticatedStorage/assets/38928133/61123bf1-6e87-4966-b837-023394a5285f">

**Comment by arzadu** [comment]
I had the same issue, sad to lose Faithless but good to know the reason! I think it's a bug from Faithless though, it also happens with Create's filters.

**Comment by P3pp3rF1y** [comment]
Is that a block shown in a limited barrel? That definitely looks like resource pack issue to be honest

**Comment by TaraciBaa** [comment]
You can fix this by changing the "Fixed" values in block.json to 0.5 (best from my tests) the path to the file is : 
Faithless.zip\assets\minecraft\models\block

**Comment by P3pp3rF1y** [comment]
That's what mc has as default values for fixed scale so yeah that would fix it. Anyway this really is a bug in faithless as I am sure you will get the the same issue with item frames where fixed transform is also used.  So I am closing this because there's nothing to take care of on my side.
