### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by lonevox** [P3pp3rF1y/SophisticatedStorage#334]
Could this be uploaded to Modrinth? It is one of the only mods in my pack that isn't on Modrinth so an upload there would be awesome! If a Modrinth release isn't planned, is it okay to distribute your jars in my pack (the actual jar file, not a link)?

**Comment by P3pp3rF1y** [comment]
I may distribute it there in the future, but don't have those plans at the moment. Otherwise happy to have my mod included / distributed in a pack on modrinth.

**Comment by P3pp3rF1y** [comment]
and with that I am closing this
