### ISSUE TITLE
Fast pick SHIFT + M1 is crashing my game

### ISSUE THREAD

**Issue by Dan1ci0** [P3pp3rF1y/SophisticatedStorage#338]
When I go to pick up an item using SHIFT + M1 from Sophisticate Backpacks or Sophisticate Storage Chests my game crashes and I don't know why

**Comment by P3pp3rF1y** [comment]
you have a crash log? Also if you're using Smooth swapping that's likely the cause of the issue.

**Comment by Dan1ci0** [comment]
MY GOD IT WAS RIGHT THANK YOU SO MUCH

**Comment by P3pp3rF1y** [comment]
Thanks for confirming. So I am closing this.
