### ISSUE TITLE
[SophisticatedStorage for 1.19.2 and above] The Pre-dependency information setting is missing

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedStorage#344]
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/110439412/ee3adedb-3eab-499f-b0e4-efa015dbc4bc)
CurseForge 1.19.2 和更高版本少了前置信息导致PCL无法识别前置 Mod，从而无法下载前置Mod，希望尽快解决
CurseForge 1.19.2 and above lacks pre-mod information, resulting in PCL not being able to recognize pre-mods, so pre-mods cannot be downloaded.
Hope to solve it soon
Thanks！

**Comment by ghost** [comment]
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/110439412/ac9079e3-2b55-419e-8af3-085d6cdb16f0)

**Comment by P3pp3rF1y** [comment]
Thanks for letting me know, just updated that on CF

**Comment by ghost** [comment]
Just remember to add it next time

**Comment by P3pp3rF1y** [comment]
Well it's always automatically added based on previous upload. But cf changed the ui and I am guessing it either not copy this over or forgot the info during upload as I am sure I checked it for the first one, it was there and today I couldn't see it for a single upload

**Comment by ghost** [comment]
> 好吧，它总是根据以前的上传自动添加的。但是 cf 更改了 ui，我猜它要么没有复制它，要么在上传过程中忘记了信息，因为我确信我检查了它的第一个，它就在那里，今天我看不到它进行单次上传

CurseForge is trying to modify the website to make the experience worse for both developers and users
