### ISSUE TITLE
Reload Breaks Any Storage with Compression Upgrade

### ISSUE THREAD

**Issue by Darkosto** [P3pp3rF1y/SophisticatedStorage#345]
Hey!

When using custom Compression config entries, using the `/reload` command in-game will break all storage blocks that use the Compression upgrade. This means that any time a `/reload` would need to happen, I have to restart the entire client so my Sophisticated Storage blocks work properly. 

This is the entry I am currently using in the `sophisticatedstorage-server.toml` file:
```
# List of items that can be decompressed by compression upgrade and their results. Item registry names are expected here in format of "mod:itemBeingDecompressed=Nxmod:itemDecompressResult
additionalDecompressibleItems = [
  "minecraft:glowstone=4xminecraft:glowstone_dust",
  "minecraft:quartz_block=4xminecraft:quartz",
  "sf5_things:block_of_black_dye=9xminecraft:black_dye",
  "sf5_things:block_of_blue_dye=9xminecraft:blue_dye",
  "sf5_things:block_of_brown_dye=9xminecraft:brown_dye",
  "sf5_things:block_of_cyan_dye=9xminecraft:cyan_dye",
  "sf5_things:block_of_gray_dye=9xminecraft:gray_dye",
  "sf5_things:block_of_green_dye=9xminecraft:green_dye",
  "sf5_things:block_of_light_blue_dye=9xminecraft:light_blue_dye",
  "sf5_things:block_of_light_gray_dye=9xminecraft:light_gray_dye",
  "sf5_things:block_of_lime_dye=9xminecraft:lime_dye",
  "sf5_things:block_of_magenta_dye=9xminecraft:magenta_dye",
  "sf5_things:block_of_colorless_dye=9xsf5_things:none_apple",
  "sf5_things:block_of_orange_dye=9xminecraft:orange_dye",
  "sf5_things:block_of_pink_dye=9xminecraft:pink_dye",
  "sf5_things:block_of_purple_dye=9xminecraft:purple_dye",
  "sf5_things:block_of_red_dye=9xminecraft:red_dye",
  "sf5_things:block_of_white_dye=9xminecraft:white_dye",
  "sf5_things:block_of_yellow_dye=9xminecraft:yellow_dye"
]
```

SophisticatedCore: 1.20.1-0.5.116.537
SophisticatedStorage: 1.20.1-0.8.68.692
Minecraft: 1.20.1
NeoForge: 47.1.84

Let me know if you have any questions!
Darkosto

**Comment by Darkosto** [comment]
Just looked further into this and it seems as I can replicate this better by leaving an existing world with functional Compression upgrades, open another world, and then open up the 1st world. The Compression upgrades are then non-functional until a full client restart.

**Comment by P3pp3rF1y** [comment]
So as mentioned on stream I tried recreating with 
- custom CT recipes both ways - 4x feather to 1x blaze road and reverse of that recipe both shapeless
- custom CT recipe to compact only - 4x feather equals 1x blaze rod + "minecraft:blaze_rod=4xminecraft:feather" in `additionalDecompressibleItems` config

Tried loading different world and back, reloading data multiple times, but I am still unable to recreate and compression upgrade just keeps working. 

The only thoughts I have at this moment are:
- some other mod in your pack affects how events fire which causes the cache to not have correct data / not get cleared on world load
- the items that you are decompressing there for some reason are special and somehow affect this (but to be honest would be surprised if there was something there as I assume they are really simple custom items)

**Comment by P3pp3rF1y** [comment]
This was very likely solved when I changed how cache is refreshed for compacting / compression recipes so I am going to close. If you encounter this again please log a new issue for that.
