### ISSUE TITLE
where are the tank and battery upgrades?

### ISSUE THREAD

**Issue by Gitcrafter** [P3pp3rF1y/SophisticatedStorage#35]
where are the tank and battery upgrades for the storage blocks? the pump upgrades are there, but without the tank upgrade, they are useless

**Comment by P3pp3rF1y** [comment]
Tank and battery will be separate blocks in the future and when you check pumps you will notice they don't have crafting recipes which is because the don't have a use yet

**Comment by Gitcrafter** [comment]
Thanks for the reply, I totally missed, that they don´t have recipes and I´m locking forward to the new tank and battery
