### ISSUE TITLE
Packed chest causes "Rendering entity in world" crash

### ISSUE THREAD

**Issue by Orekuram** [P3pp3rF1y/SophisticatedStorage#366]
I play in an Essential server hosted by a friend. We just updated from 1.20.1-0.9.6.720 to 1.20.1-0.10.5.747.

I entered the world, crafted a packing tape, packed a gold chest full of items and the game crashed the moment it was in my inventory. I entered again and when I opened my inventory, it crashed again. I have attached the crash report here.

My friend, the host, managed to resolve the error by editing my playerdata file to move the chest to my hotbar. When I entered the world, I was able to place the chest and we continued playing normally with no further incidents. 

I think when there's a packed chest full of items in the inventory, the game is unable to render its contents and proceeds to crash. This didn't happen in the previous version (720), where I used the packing tape to move a lot of chests.

[crash-2024-03-06_01.06.00-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/14506030/crash-2024-03-06_01.06.00-client.txt)

**Comment by P3pp3rF1y** [comment]
Fixed this in the latest release on curseforge
