### ISSUE TITLE
Advanced Compacting Upgrade doesn't work in some cases

### ISSUE THREAD

**Issue by CreamyOmelet** [P3pp3rF1y/SophisticatedStorage#368]
I have an iron farm built using the create mod and i'm trying to use the advanced compacting upgrade to compact all the nuggets into ingots and ingots to blocks but it wouldn't work. Thinking I was doing something wrong I went searching for a tutorial. I found it and followed it and it still wouldn't work.

Context: I'm playing in a LAN world with a friend.

**Comment by CreamyOmelet** [comment]
Update: I tested it in a singleplayer world and it worked just fine. I really don't know why the mod works one side and not the other.

Also, forgot to mention, we're using Forge 1.20.1-47.2.20 with Sophisticated Storage 1.20.1-0.9.6.720

**Comment by P3pp3rF1y** [comment]
This works for most of the players playing on servers (also works for me when I test on server) so I will need more info on what kind of server it is (just a plain old forge server or something else) / what mod list you have there. It's either modified server not triggering the correct event or one of the mods causing the event to not trigger

**Comment by CreamyOmelet** [comment]
We figured it out, it was a mod version disparity. Thanks for trying to help though.
