### ISSUE TITLE
Advanced Hopper Filter 'Match Storage Contents' when pushing doesn't filter based on target's inventory contents

### ISSUE THREAD

**Issue by xllvrr** [P3pp3rF1y/SophisticatedStorage#369]
I am using the mod in an alpha pack for Nomifactory and have found that the Advanced Hopper Filter when set to 'Match Storage Contents' simply acts as if it is on 'Block' mode with no filters (i.e. any item just goes straight into the empty slot).

I am unsure whether this is an issue with compatibility within the modpack or whether this is an issue at the mod level, so just posting here to check (would include a mod list but it's really long so unless needed will refrain from doing so for now)

**Comment by P3pp3rF1y** [comment]
Just tested it and it's working correctly for me, but this will only filter by storage contents on pull, push obviously will push everything because it is in the storage that you are pushing from so by definition it matches storage contents.

Are you pushing stuff out perhaps?

**Comment by xllvrr** [comment]
Yes, I was using ala a hopper that could be filtered. So the push matches the contents of the Sophisticated Storage barrel rather than the target storage of the machine in question?

**Comment by P3pp3rF1y** [comment]
the match contents always applies to the storage that the upgrade is in whatever the upgrade is - you have pickup, magnet, filter upgrade, hopper upgrade that use this setting and I may be missing some.

**Comment by P3pp3rF1y** [comment]
Actually, came back to this and I already have an example of an upgrade that filters based on target inventory - Deposit upgrade. So I am going to change this mode in hopper upgrade to also filter based on the inventory that the hopper upgrade is pushing into.

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
