### ISSUE TITLE
Tag filters randomly clear

### ISSUE THREAD

**Issue by brisingraerowing** [P3pp3rF1y/SophisticatedStorage#37]
As per title. Sometimes a filter of any sort set to tag mode will clear the list. I have not found any real consistent method to reproduce this. I am not seeing this with Sophisticated Backpacks. Other filter modes don't clear.

Sophisticated Core: 0.3.6.53
Sophisticated Storage: 0.3.4.49
Minecraft: 1.18.2
Forge: 40.1.54

**Comment by P3pp3rF1y** [comment]
I will need step how to recreate as I have never seen this happening and haven't heard from anyone else regarding this and don't want to spend loads of time trying to recreate something I may not.

**Comment by brisingraerowing** [comment]
It seems completely random. I have switched between Creative and Survival a few times, and I know there was an issue with that clearing NBT stuff in 1.12.2 (not sure if that ever was changed). I *think* it was related to share tag differences between game modes.

**Comment by P3pp3rF1y** [comment]
I have tried a few things but can't recreate so I need more info / detailed steps on how

**Comment by P3pp3rF1y** [comment]
I have actually found the issue in the meantime so this will be fixed in the next release

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest release
