### ISSUE TITLE
Space inside chest/barrel/shulker etc upgrade limits causing crash

### ISSUE THREAD

**Issue by Alexhupp** [P3pp3rF1y/SophisticatedStorage#372]
I was playing ATM9 and i decided i wanted to increase my stack upgrade limit, i didnt realize this instantly but i had put a extra space in the config file behind the limit for chests which resulted in the value being "Chest|Stack_Upgrades|4 " It seems like due to this the game threw a crash [Log here](https://mclo.gs/PlO152d) i think this is interesting enough to implement potentially some way to handle or tell say a client that something had a error compared to a confusing and no error ed crash

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest update of SophisticatedCore on curseforge
