### ISSUE TITLE
Cannot place doors on Barrels

### ISSUE THREAD

**Issue by brisingraerowing** [P3pp3rF1y/SophisticatedStorage#373]
Doors can be placed on Vanilla barrels, but not any of the barrels from this mod. Could that be fixed? The structure I'm taking over uses a door on barrels as part of a wardrobe decoration, and I want to change out the vanilla barrels (that look like Spruce) with Dark Oak barrels, as most of the rest of the wardrobe is Dark Oak.

**Comment by P3pp3rF1y** [comment]
I had a feeling I made this work long while ago as part of having rails placeable on top of barrels and yup just confirmed in latest 1.20 that it just works and the same should be true for latest 1.18 / 1.19 versions. So you should be able to just update and have it work.

**Comment by brisingraerowing** [comment]
So it appears that one of my other 450-ish mods is breaking things. Great. Now to find out which one.
