### ISSUE TITLE
JEI drag does not work with filters

### ISSUE THREAD

**Issue by brisingraerowing** [P3pp3rF1y/SophisticatedStorage#38]
As per title. This works with Sophisticated Backpacks, but not Sophisticated Storage.

Sophisticated Storage: 0.3.4.49
Minecraft: 1.18.2
Forge: 40.1.54

**Comment by P3pp3rF1y** [comment]
This just works for me so I will need more info on what upgrade you're trying to filter and what you are trying to drag into it or other steps that I need to take to recreate

**Comment by brisingraerowing** [comment]
I've noticed that the Sophisticated Storage upgrade tabs do not interact with the JEI item list at all. That may be related. I'm on JEI 9.7.0.209, which is the latest release for 1.18.2.

**Comment by P3pp3rF1y** [comment]
Just tested with that version in ATM7 and pickup upgrade and I can still drag items into its filter. So I still need steps to recreate or understand what mod in your modpack is causing this.

**Comment by brisingraerowing** [comment]
I have confirmed that this is a mod conflict of some sort. Now to find which mod is being stupid.

**Comment by P3pp3rF1y** [comment]
do you have any additional info for me or should I just close?

**Comment by brisingraerowing** [comment]
I never figured this out.

**Comment by brisingraerowing** [comment]
Actually, whatever JEI fix you did in the latest release fixed this as well.

**Comment by P3pp3rF1y** [comment]
alright so this was like related to an error that could sometimes happen in JEI integration init which would cause the rest of the integration not to get loaded.
