### ISSUE TITLE
All storage disappears after exiting and re-entering world

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedStorage#384]
Using version 1.20.1-0.10.11.766 (latest of Minecraft 1.20.1 at time of writing), when I exit my world and re-enter it all my items are gone. This includes any Chest, barrel, and Shulker box. Upgrades or no upgrades (in fact, upgrades are deleted as well). I have this exact same issue as Sophisticated Backpacks. Might downgrade to see if it's just this version.
[latest.log](https://github.com/P3pp3rF1y/SophisticatedStorage/files/14657937/latest.log)
Exact same issue but under different circumstances so it might actually be a mod conflict:
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/156

**Comment by P3pp3rF1y** [comment]
I can't recreate so it looks like it's something in your modpack. Or have you got only sophisticated storage (and core) in the pack?

Also that closed backpack issue can't have anything to do with your items disappearing here as when you have storage blocks in world they just use normal vanilla storage for block entities.

**Comment by ghost** [comment]
After extensive (on and off) testing, I believe I've found the problem. There's another mod I had that's supposed to integrate the Cobblemon mod with several mods such as Sophisticated Storage called [Compatemon](https://modrinth.com/mod/compatemon). I have disabled this feature in the config and it my items from both Sophisticated Storage and Sophisticated Backpacks remain in them after closing the game. I believe I can close this issue now and I'll see if I can't contact the mod author. Sorry for the absence.
