### ISSUE TITLE
Sophisticated Storage Controller randomly refuses to link to chests and barrels

### ISSUE THREAD

**Issue by FuryAnimation** [P3pp3rF1y/SophisticatedStorage#385]
Linking storages from Sophisticated Storage mod, such as chests and barrels to the Storage Controller from that mod doesn't seem to be working properly since the version 0.10.4.745.
When placing a bunch of chests in a world and trying to link them to a Storage Controller Some chests are refusing to link. Unlinking those chests that were able to link makes it possible to link chests that were unable to link previously.

I've noticed that while playing ATM9, but I've also tested this with a clean Minecraft 1.20.1 instance and the issue persisted.
[Video demonstrating the issue](https://www.youtube.com/watch?v=p4nsAWlCSpo)

Aside from that, those chests that were linked before update remained linked, but didn't seem to function correctly. Their inventory is visible through AE2 terminal, but some items don't end up in the chests they should be routed to according to installed filter.

Versions prior the update with double chests don't seem to be having this problem.

**Comment by P3pp3rF1y** [comment]
oh, you hopefully noticed the new release of sophisticated core that fixes this issue when you closed the bug.

**Comment by FuryAnimation** [comment]
Yep. Tested it in creative. Linking seems to be working fine
