### ISSUE TITLE
Crashing using the crafting table upgrade inside the diamond chest

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedStorage#389]
My game is crashing when I try to craft an item using the crafting table upgrade inside the diamond chest

sophisticatedbackpacks-1.20.1-3.20.3.1034
sophisticatedcore-1.20.1-0.6.11.578.jar
sophisticatedstorage-1.20.1-0.10.11.766

[latest.log](https://github.com/P3pp3rF1y/SophisticatedStorage/files/14743556/latest.log)

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/54646457/b09d60f3-f541-4856-8d42-67d74c1ec6b7)

**Comment by P3pp3rF1y** [comment]
This is likely the same cause where a recipe that returns item into non existent slot used to crash crafting upgrade. I added some handling of that plus logging so closing. The log shows the recipe and what slot it tried to use so if you get that in log I will be happy to take a look at why that is happening in a new issue.
