### ISSUE TITLE
New `dropPacked` feature should not yell at the player

### ISSUE THREAD

**Issue by MuteTiefling** [P3pp3rF1y/SophisticatedStorage#395]
Packing tape is disabled when `dropPacked` is true, so this message is a little misleading:

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/9543430/0ea8cd39-6da4-4020-a6b4-e26560ace09a)

Consider instead just bypassing the message and allow breaking without sneaking.

**Comment by P3pp3rF1y** [comment]
Ahh right, somehow I totally missed this one will remove that for next version if dropPacked is true. Also should fix that name issue in there when I am at it.

**Comment by P3pp3rF1y** [comment]
There's a new release on CF which removes the message when dropPacked is true
