### ISSUE TITLE
Show/Hide Counts & Fill Levels Not Working

### ISSUE THREAD

**Issue by DiscordPF** [P3pp3rF1y/SophisticatedStorage#397]
Unable to get the counts and fill levels to show. Tried on custom modpack with only Sophisticated Storage and Sophisticated Core installed just to be sure it wasn't a compatibility error. 

Game Version: 1.20.1
Forge Version: 47.2.23
Sophisticated Storage Version: 1.20.1-0.10-20.778
Sophisticated Core Version: 1.20.1-0.6.18.597

Steps to Reproduce:
- Set up controller & at least one storage
- Set up show inventory icon
- Fill with any amount of inventory (same item)
- While holding tool, shift scroll to change to show/hide counts and show/hide fill levels
- Attempt to right click on either controller or inventory
- No result/impact

**Comment by P3pp3rF1y** [comment]
Have you actually switched to an empty hand after doing this to see what it looks like? There's a minor change in how these are rendered when you switch on/off and still hold the tool, but without the tool in hand you should see that these are really hidden / shown

**Comment by DiscordPF** [comment]
I just double checked and I still don't see the counts/fill levels shown even when I remove the tool from my character's inventory. If it's working for you then it must just be a bug for me. Not sure what's interfering with it, though.

**Comment by P3pp3rF1y** [comment]
what version of the mod do you actually have?

**Comment by DiscordPF** [comment]
I have the version installed that was referenced above. 

Game Version: 1.20.1
Forge Version: 47.2.23
Sophisticated Storage Version: 1.20.1-0.10-20.778
Sophisticated Core Version: 1.20.1-0.6.18.597

**Comment by P3pp3rF1y** [comment]
Sorry I was looking only at the email updates and those somehow don't show me the original message with version

Anyway now just rereading the original message are you actually trying this with Limited barrel. Based on "Set up show inventory icon" I am suspecting you tried with regular barrel / chest that don't support showing these.

I guess if people are getting confused regarding this I could add a message to show when storage that doesn't support setting these is right clicked.

**Comment by DiscordPF** [comment]
That makes sense. I can confirm that I was not using a limited barrel. I was using a regular barrel. Thanks for letting me know what I was doing wrong. I appreciate the quick and thorough responses!
