### ISSUE TITLE
Is copper and gold chest supposed to have the same storage space and iron having less then copper?

### ISSUE THREAD

**Issue by Tutas449** [P3pp3rF1y/SophisticatedStorage#399]
I don't know if its something from my side but cooper and gold chests have the same storage space of 5 rows and upgrading cooper to iron actually lower space by a row

**Comment by P3pp3rF1y** [comment]
Sounds like your pack changes number of slots and they haven't changed copper chest from its default when it was released

**Comment by Tutas449** [comment]
Is there a way to reconfigure it myself? Its a part of a modpack called SteamPunk [LPS]. I tried changing it ingame through the mod tab but i wasn't able to

**Comment by P3pp3rF1y** [comment]
It's in standard server configs so just look for sophisticatedstorage-server.toml in your world folder or in defaultconfigs folder (that will apply to any new world you create)
