### ISSUE TITLE
Dupe Bug - Sophisticated Barrels  

### ISSUE THREAD

**Issue by FoxSketchez** [P3pp3rF1y/SophisticatedStorage#4]
Mod pack : atm7  version: 0.3.21 / mc 1.18.2

Having two or more barrels (in a stack) in a crafting table with any dye will dupe them once dyed

I have tested this with a Normal crafting table, Applied Energetics crafting terminal, 
and a Metal crafting table from Engineers Decore 
with all producing the same dupe

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this just fixed it and will release a fix to SophisticatedCore shortly

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release of sophisticated core on curseforge
