### ISSUE TITLE
Interaction with Extended AE causing Crash to Desktop

### ISSUE THREAD

**Issue by Affront7546** [P3pp3rF1y/SophisticatedStorage#401]
### Describe the bug

Occasionally the game will crash with a "Ticking GridNode" error.
This has occurred on All The Mods 9, versions 0.2.56, 0.2.57, and 0.2.58.

- 0.2.56 the crash occurred after the game was running for a couple of hours, and again immediately if the world is reloaded
  - sophisticatedcore-1.20.1-0.6.12.589
  - sophisticatedstorage-1.20.1-0.10.12.768
  - (same since modpack version 0.2.55)
- 0.2.57 the crash occurred within 10 seconds after the game loaded on a previous world save
  - sophisticatedcore-1.20.1-0.6.18.597
  - sophisticatedstorage-1.20.1-0.10.20.778
- 0.2.58 the crash occurred within 10 seconds after the game loaded
  - same mod versions

The configuration I have setup is a tag export bus connected directory to a sophisticated storage controller.

### Minecraft version

1.20

### On which mod loaders does it happen?

Forge

[All The Mods 9 Version 0.2.57](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5282232)

### Crash Logs

[crash-2024-04-24_12.22.40-server.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/15111001/crash-2024-04-24_12.22.40-server.txt)

[crash-2024-04-24_09.05.55-server.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/15111000/crash-2024-04-24_09.05.55-server.txt)

**Comment by P3pp3rF1y** [comment]
I fixed this one back in May so just closing now
