### ISSUE TITLE
Using packing tape on a full double chest with stack upgrades will cause it to spew items on the ground

### ISSUE THREAD

**Issue by Castone22** [P3pp3rF1y/SophisticatedStorage#407]
Replication:
1. Fill a netherite double chest with 2 diamond stack upgrades to capacity.
2. Use Packing tape
3. Observe the itemsplosion as your minecraft client probably freezes.

Also applies to mek boxes.

**Comment by P3pp3rF1y** [comment]
Are you using sophisticated storage packing tape or the one from packing tape mod?

The behavior with mek boxes is correct and so it is if you're using packing tape mod. The reason is that you're only packing half of the chest and only one half has stack upgrades in it so the half that loses access to stack upgrades must drop contents that no longer fit.

**Comment by Castone22** [comment]
Sorry, this was with the sophisticated state packing tape, after that happened I didn't want to attempt the packing tape mod after I saw the mods own tape do this

**Comment by P3pp3rF1y** [comment]
And when that hat happens is the whole double chest packed and then drops as a whole when broken?

**Comment by Castone22** [comment]
One side gave me a warning that i couldn't break the chest because it would
spill items on the floor, the other got packed and upended it's contents on
the floor.  I actually want to double check something.  I specifically
tried to craft this mods packing tape but I'm wondering if atm9 did
something weird like having both use the same recipe

**Comment by Castone22** [comment]
I double checked, the recipes are different, trying it with a less filled chest acted like i'd expect (packed the whole chest)  It seems like it may only fail when the chest is over a threshold.

**Comment by Castone22** [comment]
Alright, i'm completely unable to replicate this in a creative world... so either it's an SMP thing or somehow i ended up with the wrong type of packing tape (highly possible).  If you feel comfortable you can just close this.

**Comment by P3pp3rF1y** [comment]
closing...
