### ISSUE TITLE
Compability with threshold switches from create

### ISSUE THREAD

**Issue by EKE-E** [P3pp3rF1y/SophisticatedStorage#408]
For example in limited barrel one stack  of items for threshold switch = 100% it's capacity

**Comment by P3pp3rF1y** [comment]
That sounds like request to create to support working with standard slot capacity and determining how full they are based on that.

Or why do you feel this should be added on sophisticated storage side?

**Comment by P3pp3rF1y** [comment]
closing given no follow up
