### ISSUE TITLE
[BUG] - Internal Exception Forge server

### ISSUE THREAD

**Issue by Xenxia** [P3pp3rF1y/SophisticatedStorage#411]
Version Forge : 47.2.0
Version Minecraft : 1.20.1
Version Mod : 0.10.24.801

Error when I join my server :  
`
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: net.p3pp3rf1y.sophisticatedstorage.crafting.BaseTierWoodenStorageIngredient@643368e
`

**Comment by P3pp3rF1y** [comment]
This was fixed later yesterday already so just download the latest version.
