### ISSUE TITLE
Kubejs 1.20.4 Neoforge compat issue

### ISSUE THREAD

**Issue by Saereth** [P3pp3rF1y/SophisticatedStorage#413]
Not sure if this issue is on Kube's side or Sophisticated but with kubejs if I add any custom recipes at all then all of sophisticated backpack/storage recipes end up removed.

Steps to reproduce:

install sophisticated storage/core/backpacks and kubejs + dependencies on a 1.20.4 neoforge instance
make a simple servrer script to add a recipe such as 

```
ServerEvents.recipes((event) => {

  event
    .shaped("minecraft:beehive", ["PPP", "SSS", "PPP"], {
      P: "#minecraft:planks",
      S: "minecraft:sugar",
    })
    .id("ftbneotech:hivealternate");

});
```

All subsequent reloads/pack relaunches will have missing recipes for all of  Sophisticated backpacks/storage items.

This doesn't seem to impact any other mods that I've found yet.

**Comment by TheonlyTazz** [comment]
Appendum:
This can be potentially caused by the `neoforge:conditions` inside the recipes JSONs

if switched back to `conditions` it works again.

**Comment by P3pp3rF1y** [comment]
@TheonlyTazz what do you mean by switched back to conditions? What is evaluating those conditions then?

**Comment by TheonlyTazz** [comment]
Good Question 😅  i only tested by removing that and it showed up the recipes, so i "assumed" that  thats causing the issue, guess i'll have to dig in further

**Comment by P3pp3rF1y** [comment]
@Saereth I was going to test with kubejs, but I am unable to find 1.20.4 version of it. I can see on CF the version listed among versions that are supposedly supported, but when I filter by it no file for download is listed. Did you get it there or somewhere else? Perhaps they pulled the version because it had some bad bug that guaranteed pulling it?

**Comment by P3pp3rF1y** [comment]
Alright found the alpha release there. Joined their discord and can see that they have an issue for conditional recipes not working with kubejs so you will need KubeJs To fix this.

**Comment by P3pp3rF1y** [comment]
And now I see that one of the last comments is from you :D
