### ISSUE TITLE
Controller unlkinking issue.

### ISSUE THREAD

**Issue by dagepyro** [P3pp3rF1y/SophisticatedStorage#415]
The storage controller will not unlink from a locate if the item is broken before unlinking. When placing down a different block it will show as it is connected to the controller.

![2024-05-10_13 20 28](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/4659634/cbeb69b2-f586-47ee-a4b6-564b73939b73)

I am using sophisticatedcore-1.20.1-0.6.22.611, sophisticatedstorage-1.20.1-0.10.25.804

**Comment by P3pp3rF1y** [comment]
How have you broken that storage block that was in that place? Can you give me steps I can use to recreate?

**Comment by P3pp3rF1y** [comment]
Any additional info you can provide here? Or should I just close?

**Comment by dagepyro** [comment]
I placed the storage link on an inventory. connect the link to the
controller. I then broke the link before unlinking it from the controller. After removing the link placing any block down will cause it to show as linked.

**Comment by P3pp3rF1y** [comment]
And I am unable to recreate. 

So I will need steps that I can repeat that will allow me to recreate the issue and fix it then.

**Comment by dagepyro** [comment]
I was using the Storage I/O and not the storage link. The storage input,
the storage output, and the storage I/O are the blocks that are creating
the issue. The storage link does not have that issue.

**Comment by P3pp3rF1y** [comment]
I have fixed this issue that affected all 3 storage IO blocks in the latest release
