### ISSUE TITLE
missing crafting recipe

### ISSUE THREAD

**Issue by Lucky-56** [P3pp3rF1y/SophisticatedStorage#416]
**Bug description:**
Basic to Iron Tier Upgrade crafted from Basic to Copper Tier Upgrade is missing

**Versions:**
Minecraft version: 1.20.1
Sophisticated Core version: 0.6.22.611
Sophisticated Storage version: 0.10.25.804
Forge version: 47.2.31

**Images:**
![copper_to_iron_upgrade](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/55949451/196a22ce-a975-44fc-a21d-df8d998817a4)

**Comment by P3pp3rF1y** [comment]
What version is that?

**Comment by Lucky-56** [comment]
omg very sorry will update in a sec

**Comment by P3pp3rF1y** [comment]
actually looks like I never added this recipe in the first place so that was missing since copper stuff was introduced

**Comment by Lucky-56** [comment]
thought so, copper stuff is a very welcome addition btw ^^

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
