### ISSUE TITLE
Support customizing new boxes, buckets, or shadow boxes and their row and column numbers through config

### ISSUE THREAD

**Issue by gjmhmm8** [P3pp3rF1y/SophisticatedStorage#418]
Support customizing new boxes, buckets, or shadow boxes and their row and column numbers through config

**Comment by P3pp3rF1y** [comment]
I have no idea what you're referring to here, there are no boxes, buckets or shadow boxes in sophisticated storage. Did you mean to log this to a different mod?

**Comment by P3pp3rF1y** [comment]
closing given no feedback
