### ISSUE TITLE
Duplication when crafting in Refine Storage

### ISSUE THREAD

**Issue by puggan** [P3pp3rF1y/SophisticatedStorage#421]
Item duplication when crafting items from Sophisticated Storage using Refine Storages Crafting Grid.

reproducable in 0.10.25.804
All Versions: 
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/eddb708b-0e4e-4f0e-8444-98b210a231b9)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/b78a213a-5d22-4a9c-9343-42c9e56b031b)

Also reported to Refine Storage at https://github.com/refinedmods/refinedstorage/issues/3682

Setup for reproducing:
* Refine Storage Crafting Grid
* Refine Storage Controller (Creative to skip adding powersource)
* Refiine Storage External Storage
* Netherite chest with 2 stack upgrades
* 18 stacks of redstone dust
![2024-05-18_14 41 41](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/06cbd806-76e0-4928-b01f-f86c9c6fde7f)
![2024-05-18_14 41 39](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/649d8712-3244-48bd-9f95-12f04291042e)

Reproduce:
* Use the Crafting Grid to Craft Redstone Blocks, by shift-clicking to make a full stack

Expected:
* 18 stack of redstone -> 2 stack of redstone block

Current Behaviour:
* 18 stack of redstone -> 9 stack of redstone block

![2024-05-18_14 48 19](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/866668/8da7eba4-c65f-4589-8437-83ad0c83653d)

**Comment by puggan** [comment]
variation test:
* Taking out the Stack Upgrades removes the problem.
* Switching the chest to a barrel with one stack upgrade also gives the same problem.

**Comment by P3pp3rF1y** [comment]
Yes that is a known bug in Refined Storage please report / add to the bug report they already have on their side.
