### ISSUE TITLE
[1.20.1] Hopper upgrade crash

### ISSUE THREAD

**Issue by Arman20004** [P3pp3rF1y/SophisticatedStorage#422]
I was playing on skyblock and noticed that if you place storage of any kind with hopper upgrade at lowest level facing into the void your game just crashes

**Comment by P3pp3rF1y** [comment]
Could you share the crash log?

**Comment by Arman20004** [comment]
Link to crash log:

https://mclo.gs/Sr1ndp5

**Comment by jammer312** [comment]
Also happened to me today on a server. I've placed a chest at the lowest level in the end and slotted an advanced hopper upgrade into it, and right after that the server crashed, and whenever I joined it crashed again. I tried to reproduce it in singleplayer in overworld, but it didn't lead to a crash, so it might be that it only affects servers

**Comment by jammer312** [comment]
https://pastebin.com/04pxYgB6 relevant crash log
I bet it's because the upgrade tries to access a block outside of world boundaries (so I guess the same happens when you place a container with a hopper upgrade at the highest point of the world)

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest versions
