### ISSUE TITLE
Chest upgrade will also upgrade half of an adjacent double chest

### ISSUE THREAD

**Issue by uhthomas** [P3pp3rF1y/SophisticatedStorage#426]
A single chest upgrade should only be able to upgrade a single chest at a time, but it can upgrade two chests at once in certain scenarios.

Place 3 chests like so.

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/9749173/80a612be-8dd4-4341-99f1-45d7db997943)

Upgrade the left-most chest.

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/9749173/ae1b5410-2be3-4907-8cd8-6278bc89ef49)

Observe two chests were upgraded, and now the double chest is broken.

**Comment by P3pp3rF1y** [comment]
That's an interesting one and I just confirmed in dev environment so I will have this fixed for the next release.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release
