### ISSUE TITLE
[1.20.1] Duplication glitch with Valkyrien Skies Eureka/Clockwork

### ISSUE THREAD

**Issue by shoolepak** [P3pp3rF1y/SophisticatedStorage#427]
While assembling/disassembling a ship, the items inside any chests or barrels added by this mod get dropped, but they don't disappear from inside of the containers, essentially enabling an infinite duplication glitch, as repeated disassembling/assembling drops the items each time.

This bug is NOT present with shulker boxes or backpacks, although shulker boxes do not render the upper lid while on assembled ships (but this might also be a fault of another mod, I didn't test this properly).

I admittedly don't know how this works exactly, but since it only affects chests and barrels I imagine it wouldn't be too hard to fix, since it already works as intended with backpacks and shulkers (the items just stay inside, nothing gets duped and dropped).

**Comment by P3pp3rF1y** [comment]
This is on valkyrian for not clearing the storage before breaking it. But someone has create a compat for this already https://www.curseforge.com/minecraft/mc-mods/valkyrienskiessophisticatedstoragecompat

**Comment by shoolepak** [comment]
> This is on valkyrian for not clearing the storage before breaking it. But someone has create a compat for this already https://www.curseforge.com/minecraft/mc-mods/valkyrienskiessophisticatedstoragecompat

Tkanks for the reply! The compat unfortunately is not for 1.20.1, but since I really want this in the modpack I'm creating, and the compat is open source, I might try to compile it myself for that version.
