### ISSUE TITLE
Double Chest Plays Sound Twice and My Doctor Said to Call You

### ISSUE THREAD

**Issue by Darkosto** [P3pp3rF1y/SophisticatedStorage#433]
Dear staggeringly knowledgeable mod developer,

I am once again coming to you with a gravely important quest. I very much appreciate that you've added double chests to Sophisticated Storage because I am in love with double chests. There's nothing better!

Having said that, there is a slight problem. You're playing the sound of the chest opening twice instead of just once. It's bothering me and I can't let it go. Please advise on how I may mentally cope with this ailment.

Yours truly,
Streamerperson Darkosoto
(this is not an ad! Pls don't ban me!)

MC: 1.20.1
Neoforge: 47.1.106
Sophisticated Storage: 0.10.25.804
Sophisticated Core: 0.6.22.611

**Comment by P3pp3rF1y** [comment]
Dear esteemed connoisseur of all things mod-related,

Your profound concern has been heard across the digital cosmos, and I am pleased to report that your journey toward mental serenity has reached a triumphant conclusion. The glitch you so courageously endured, like a true warrior of Minecraft realms, has been vanquished in the latest release. No longer shall the sound of your beloved chest echo twice, haunting your every click.

Rejoice, for peace has been restored! Update now, and may your storage adventures continue without auditory disturbance.

Yours humbly, The Bug-Squashing Developer
(We promise, this isn’t an ad either. Please keep adventuring!)
