### ISSUE TITLE
Using packing tape on netherite double chest with stack upgrades cause item explosion

### ISSUE THREAD

**Issue by Kedu-Astronauta** [P3pp3rF1y/SophisticatedStorage#434]
Same issue as related on the issue #407 

**Minecraft Version:** 1.20.1
**Forge:** 47.2.20
**Modpack:** None, one I made just to test this bug
**Mods in the pack:**
- Sophisticated Core: 0.6.22.611
- Sophisticated Storage: 0.10.25.804
- Sophisticated Backpacks: 3.20.5.1044
- Pipez: 1.20.1-1.2.12
- Functional Storage: 1.20.1-1.2.11
- Titanium: 3.8.28

**How to replicate:**
Put a netherite double chest on the ground.
Put a Advanced Compacting Upgrade and two Stack Upgrades Tier 5.
Fill the chest completely with Iron Bars, should now have thousands of Blocks of Iron and some Iron Bars (I used Functional Storage and Pipez to fill it fast).
Now with the packing tape, try to pack any of the sides of the chest, it will cause a item explosion.

**Video:** https://youtu.be/6Cwxl9sWjMc

**Comment by Kedu-Astronauta** [comment]
Found the cause!
This bug is caused when the Advanced Compacting Upgrade is present in the chest.

Video: https://youtu.be/QO8OMoCbS34

**Comment by ThinkWithPbody** [comment]
I don't have advanced compacting upgrade and I still run into this issue consistently with one of my double chests. Once I removed the disk upgrade it worked.

**Comment by Kedu-Astronauta** [comment]
So it's probably related to the double chest having multiple upgrades causing some weird interaction when packing.

**Comment by mjory80** [comment]
I tested this in the FTB Neotech modpack, which has "dropPacked = true", so packing tape is always applied.  I found that the chest would always explode the items out when I would break the right-hand side of the chest.  If I broke the left side, it would drop the chest with the items contained.

**Comment by P3pp3rF1y** [comment]
So this conversation is actually about two different issues - one is an issue where tickable upgrades in packed double chest caused it to spill out items when broken. And the second one is breaking right side of the double chest when `dropPacked` is true caused item spilling as well.

Both of these are now fixed in the latest releases for 1.20.1 and 1.21.
