### ISSUE TITLE
Linking tool memory overload crash

### ISSUE THREAD

**Issue by Mindcool25** [P3pp3rF1y/SophisticatedStorage#436]
Ran into an issue today playing with the ATM 9 modpack, and ran into a crash when moving my base. I had a storage controller set up in the old one in the overworld, and was moving my base to the Other dimension, which was over 50k blocks away from the original base coordinates wise, and when I used the linking tool to set up my drawers again, it had kept the coordinates  selected from before, which lead to my game eating up all the memory I gave it and it crashed.

**Sophisticated Storage Version:** 0.10.25.804
**Minecraft Version:** 1.20.1

I'll try doing the same thing on a instance with just the storage mod installed and see if the same thing happens. 

A potential fix that I can think of is limiting the size of the multiblock selection, but I haven't looked through the source yet to see how possible that is. I'll look into it though.

**Comment by Mindcool25** [comment]
wrong mod my bad

**Comment by P3pp3rF1y** [comment]
well, just close the bug then
