### ISSUE TITLE
Add threshold switch support

### ISSUE THREAD

**Issue by Rodrigo816** [P3pp3rF1y/SophisticatedStorage#440]
So the threshold switch from create seems to only see one stack in the drawer and base it's fullness from that, so eg. you put 32 items for threshold switch its 50% even if u can still fit thousands of items more.

![image3](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/12116265/8c5a4c4b-9024-4760-8906-63cad9a9136b)
![image2](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/12116265/92374982-5307-4234-a79b-0d2b5785d5e8)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/12116265/dec45949-01ef-4fe1-8dfc-f32240840f96)

**Comment by Rodrigo816** [comment]
Look at this:
https://github.com/Creators-of-Create/Create/pull/6492
I think it fixes it? why is not accepted?

**Comment by P3pp3rF1y** [comment]
This is definitely on create to fix. Looks like they just assume that single slot can have maximum of 64 of an item. And you will need to ask them about why that pr isn't merged yet.
