### ISSUE TITLE
can't upgrade stack upgrade on barrel

### ISSUE THREAD

**Issue by Spongman** [P3pp3rF1y/SophisticatedStorage#441]
pack: Craft to Exile 2

I have a 'Limited Spruce Barrel II' with a 'Stack Upgrade Tier 1' installed, and it's full of items and I want to upgrade the upgrade. I have built a 'Stack Upgrade Tier 1 Plus' (copper), but I can't for the life of me get it to upgrade the barrel. how do i do that?

**Comment by P3pp3rF1y** [comment]
You can't swap it for the other upgrade in gui?

**Comment by Spongman** [comment]
there's a gui ?

**Comment by Spongman** [comment]
looks like it's supposed to be `<Sneak>` + `<Use Item/Place Block>`, but that doesn't open a GUI for me.

**Comment by P3pp3rF1y** [comment]
are you trying that with an empty hand?

**Comment by Spongman** [comment]
weird. i tried it in a 1.20.1 instance with SS v0.10.25.804 and it works fine. must be something else in the modpack messing with it.
going to try an empty instance with the same versions (MC/Forge & SS) from the modpack.

**Comment by Spongman** [comment]
hmmm. works fine (doesn't repro) with
- MC 1.20.1
- Force 47.2.18
- SC 0.6.3.553
- SS 0.9.6.720

**Comment by P3pp3rF1y** [comment]
Sounds like something in your modpack messes with block interaction so you would need to figure out what mod it is and report to them

**Comment by Spongman** [comment]
yeah, i'll keep an eye open...
