### ISSUE TITLE
Crash when working together with Integrated Dynamics and AE2 auto crafting

### ISSUE THREAD

**Issue by suoliangao** [P3pp3rF1y/SophisticatedStorage#443]
Modpack: ATM9sky_1.0.6
The server crashes when I'm trying to craft some stack upgrades using AE2 auto crafting system.
Some limited barrels are connected together by a controller and connected to my AE system with storage bus.
Also, a integrated dynamics logistics system was also connected to the same controller to move items form the sieving system to the storage system.
The crash seems happens when the compression upgrade try to compress materials.
The crash happens randomly on the server, not tested in a single player world.
The crash report is attached below.
[crash_report.txt](https://github.com/user-attachments/files/16132921/crash_report.txt)

**Comment by P3pp3rF1y** [comment]
I can see where it crashes but I am unable to figure out how compression upgrade gets into that state or recreate the crash. I am adding a bit of handling of the invalid condition when it would crash previously and logging of the exact state the compression upgrade is in to hopefully help in the future if anyone encounters this.

**Comment by P3pp3rF1y** [comment]
I have released a new version with the logging included so closing this, feel free to either reopen or create a new one if an error related to this gets logged.
