### ISSUE TITLE
Run inventory interaction ugprades keybind causes crash on some modded blocks

### ISSUE THREAD

**Issue by Saereth** [P3pp3rF1y/SophisticatedStorage#447]
Neoforge 1.20.4 - 20.4.237
sophisticatedstorage-1.20.4-0.10.24.802
sophisticatedcore-1.20.4-0.6.21.608

Steps to reproduce:
put down a laser node from LaserIO and while lookint at it press the key bind for inventory interaction upgrade resulting in a crash

Crash log:
https://mclo.gs/f4fQVYQ

**Comment by P3pp3rF1y** [comment]
This one will be for Dire because side being null is completely valid value and the interaction should get a not sided item handler. So the fix will be needed on LaserIO side as anything else that will try to get an unsided item hadler from it will crash the same way.
