### ISSUE TITLE
IndexOutOfBoundsException causes crashes when i download and upload stuff

### ISSUE THREAD

**Issue by Sunflower47** [P3pp3rF1y/SophisticatedStorage#448]
Today i added Sophisticated Storage and Sophisticated Backpack to my custom modpack (modpack worked well before). When i use Shift + Left Click to download or upload stuff, game crashes. It happens only with mod storages (backpack too)

Minecraft 1.20.1
Forge 47.2.19
sophisticatedbackpacks-1.20.1-3.20.5.1044
sophisticatedstorage-1.20.1-0.10.25.804
sophisticatedcore-1.20.1-0.6.22.611

[crash-2024-07-27_05.28.19-client.txt](https://github.com/user-attachments/files/16398608/crash-2024-07-27_05.28.19-client.txt)
[crash-2024-07-27_05.51.01-client.txt](https://github.com/user-attachments/files/16398609/crash-2024-07-27_05.51.01-client.txt)
[crash-2024-07-27_06.23.55-client.txt](https://github.com/user-attachments/files/16398610/crash-2024-07-27_06.23.55-client.txt)

**Comment by P3pp3rF1y** [comment]
Just don't use smooth swapping they have been breaking my mod as well as other mods for quite a while and it doesn't seem they want to fix the issue Just drop that mod and issue is fixed
