### ISSUE TITLE
storage controller will not recieve items

### ISSUE THREAD

**Issue by Thumper2082** [P3pp3rF1y/SophisticatedStorage#451]
In a modpack i have made, the controller will not recieve items whether it be from hoppers or creates smart chutes, any ideas as to a fix? I have tried using a storage input adjecent to a controller but this did not work either

Edit: ignore this, modifying the modpack confused everything, breaking storage and replacing them fixed it

**Comment by P3pp3rF1y** [comment]
closing given the edit
