### ISSUE TITLE
Double chest and hopper upgrade

### ISSUE THREAD

**Issue by Blaven4** [P3pp3rF1y/SophisticatedStorage#459]
Is there a way that double chest with hopper upgrade would pass items to two targets beneath it? When I just simply put the chest on them and add hopper upgrade, set it to Push on the bottom it passes items only to one of them, choosing based on which half of chest was placed first I think

Minecraft Java 1.20.1 
Soph Core ver. 0.6.12.589
Soph Storage ver. 0.10.12.768

**Comment by P3pp3rF1y** [comment]
This is now fixed in the latest release on CF
