### ISSUE TITLE
Sophisticated storage crashes neoforge server on 1.21 when trying to craft storage controller

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedStorage#460]
Server crashes when trying to craft a storage controller using a barrel from sophisticated storage. This only happens when connected to a standalone server, and works fine when done on client on integrated server.

log of crash: https://mclo.gs/1tPScVl

I believe the latest commit to src/main/java/net/p3pp3rf1y/sophisticatedstorage/item/BarrelBlockItem.java
makes use of a library that isn't available to standalone servers.

**Comment by rodopoulos1** [comment]
same here

**Comment by P3pp3rF1y** [comment]
Fixed this in a build released yesterday
