### ISSUE TITLE
Compacting Upgrade Refinement

### ISSUE THREAD

**Issue by westriel** [P3pp3rF1y/SophisticatedStorage#462]
I'm not sure if this is something that has been suggested before or not but I'm interested in a compacting upgrade either option within the upgrade or further upgrade/refinement that would make it work similar to how Compacting Drawers from Functional Drawers and its predecessors works (where it stores as the highest compressed version of the block but when you run out of the lower material it will decompress and make more). Maybe this only works if you have a locked slot for the items (in chests) or maybe it only works in limited barrels. Not entirely sure how implementation would go but I think it would be a useful feature.

Cheers and thanks for all the work you do!

**Comment by P3pp3rF1y** [comment]
Just use compression upgrade for that which does exactly this.
