### ISSUE TITLE
There are no maple chest version.  🤷‍♀️

### ISSUE THREAD

**Issue by SirTwsted** [P3pp3rF1y/SophisticatedStorage#464]
Hi, I was playing ATM-10 mod pack yesterday, and for some odd reason I can not create maple chests version.  🤷‍♀️
Anyway,  just wanted to point that out.  😉

Thanks  🥰

**Comment by P3pp3rF1y** [comment]
Why should there be a maple version? There's no maple in vanilla and at the moment storage only has wood variants for vanilla woods. 
If you're asking for support of modded wood types that's much bigger task to add

**Comment by SirTwsted** [comment]
I just found out that the maple wood is from a mod.  I didn't know sorry.  🤷‍♀️
