### ISSUE TITLE
CTD while swapping backpacks with JDT Fuel Canister

### ISSUE THREAD

**Issue by Evan109** [P3pp3rF1y/SophisticatedStorage#468]
crash log: https://pastebin.com/PJgMgyah
world file: https://drive.google.com/file/d/1FNUJja34p-K544JYWWmRE0m6J-p_VZdz/view?usp=drive_link
Sophisticated Core 0.6.31 for 1.21
Sophisticated Storage v3.20.9 for 1.21
Sophisticated Backpacks v0.10.26 for 1.21
Loaded with the modpack Direwolf20 v11 ver. 1.0.0 for 1.21

Being a junior programmer, I investigated the crash log and originally opened an issue under Just Dire Things, linked here:
https://github.com/Direwolf20-MC/JustDireThings/issues/161
As JDT's Fuel Canister is front and center in the crash log.
Direwolf then reviewed the logs and communicated that he believes this is caused by sophisticated storage.

The crash's situation is difficult to reproduce, but the world file linked above will always crash on the first tick it's loaded.
Estimated reproduction steps: I'm unable to reproduce
Make a gold backpack with a blast furnace addon, put a JDT fuel canister inside and use it to smelt some vanilla ore.
Additionally, insert the Crafting Table and Anvil upgrades.
Pick up a mob-dropped backpack with loot inside and open it with the backpack hotkey (B by default for me) while hovering over it in the inventory.
Instantly freeze and CTD. Reopening MC and loading the world results in the same error:
An internal Server Crash referencing the JDT fuel canister:

Description: Ticking entity
java.lang.RuntimeException: Invalid stack 1 justdirethings:fuel_canister for slot 1

Attempted Fix Steps
I tried to remove the item with NBT editing, but that resulted in further errors
I removed JDT from my modlist and the world loaded like normal.  Saving and re-enabling JDT did not cause recurrence.

I will try to help with any information I can, ask away.

**Comment by P3pp3rF1y** [comment]
I fixed this issue a few days back the pack just needs to update sophisticatedcore to get the fix.
