### ISSUE TITLE
Crashing when crafting with a sophisticated barrel

### ISSUE THREAD

**Issue by Wormisduh1** [P3pp3rF1y/SophisticatedStorage#474]
Hi im not sure if this is a sophisticated storage issue but i was recommended to post here i am playing atm10 and whenever you put an item in a crafting grid with a sophisticated barrel it crashes the game because the barrel is trying to change appearance to that block. this causes constant game and server crashing. i only first noticed it when using this mod with AE2 but it happens in any crafting grid. the version i am using is 1.21-0.10.35.862

**Comment by Wormisduh1** [comment]
i am noticing its fine on singleplayer just causes crashing on a server

**Comment by P3pp3rF1y** [comment]
I need the actual crash log to be able to do anything here.

**Comment by P3pp3rF1y** [comment]
anything you can add here or should I just close?

**Comment by P3pp3rF1y** [comment]
closing given no response
