### ISSUE TITLE
[Question] Chests Now Being Labeled as Acacia

### ISSUE THREAD

**Issue by Darkosto** [P3pp3rF1y/SophisticatedStorage#495]
Hey P3pp3r1y!

It's your favorite person here again! I just updated my Sophisticated mods and am getting a strange issue. I'm not 100% sure if this is intended or if I can do something to alleviate the problem:

Any Sophisticated Storage chest that is picked up and placed back down now is labeled as an Acacia Chest: 
![image](https://github.com/user-attachments/assets/6cab09f9-0506-4357-8ea2-245ee7a7b029)

Am I able to change this label or will all of my chests say "Acacia Chest" from now on? I've had some questions about whether or not this is a bug so I think it might be helpful if I was able to alter it accordingly. If not, no worries and thank you very much for being awesome. I hope you're doing well! <3

Darkosto

MC: 1.20.1
Forge: 47.3.0
sophisticatedcore-1.20.1-0.6.32.707
sophisticatedstorage-1.20.1-0.10.41.895

**Comment by P3pp3rF1y** [comment]
Fix in the latest release on CF
