### ISSUE TITLE
Config option for Shulker Box item blacklist

### ISSUE THREAD

**Issue by kkylern** [P3pp3rF1y/SophisticatedStorage#498]
Here on the image you can see that I can put portable storages from other mods:
Sack (Supplementaries), Toolbox (Create), Luggage (Luggage), Bundle (Minecraft)
![image](https://github.com/user-attachments/assets/ec408dba-af23-4888-8f8d-86161cbd7669)
Can you add config option to blacklist items from shulker box by item id and item tag?

**Comment by P3pp3rF1y** [comment]
there are already config options for that `disallowedItems` and `containerItemsDisallowed`

**Comment by kkylern** [comment]
Oh, I see, it is located in `Server Config`, not that obvious. Thank you!
