### ISSUE TITLE
having smooth lighting off makes limited drawer fronts dark

### ISSUE THREAD

**Issue by 800020h** [P3pp3rF1y/SophisticatedStorage#501]
neoforge
sophisticatedstorage-1.21-0.10.44.906
![2024-10-07_00 59 43](https://github.com/user-attachments/assets/b76dddce-3f9d-4b58-b9d4-ea748f989a74)
having smooth lighting off makes limited drawer fronts dark
fuctional storage doesn't have the issue (idk what it does differently)

**Comment by 800020h** [comment]
with a block it looks like this
![2024-10-07_01 13 45](https://github.com/user-attachments/assets/d26f4130-cec5-4fd5-b7c0-a2c6015baca9)

**Comment by P3pp3rF1y** [comment]
yes that is true, unfortunately alternative to that is that smooth lighting would look worse and light would pass through barrels 
as well and because most of the people play with smooth lighting I made a decision to be good with this rendering dark without it and looking much better with.

**Comment by 800020h** [comment]
functional storage drawers don't let light through, and don't look bad with smooth lighting on

**Comment by P3pp3rF1y** [comment]
That's because they use more performance intensive rendering for the items. I only have that for items that require it like chests or in cases where item keeps changing way too often. In those cases the rendering won't be dark without smooth lighting either.

**Comment by 800020h** [comment]
would it be possible to have a config to move the item model out so it's flush with the front like the block model?
so it doesn't get darkened on the front face

**Comment by P3pp3rF1y** [comment]
you can convert the barrel to flat face one - just place it in crafting table by itself - and that will make the barrel render without the indent and the item should render without the shadow in that case

**Comment by 800020h** [comment]
that is a satisfactory solution
however there doesn't seem to be a way to learn it ingame
