### ISSUE TITLE
[BUG] 1.18.2 socket error crash with full barrel setup interacting to me

### ISSUE THREAD

**Issue by ChimeraGaming** [P3pp3rF1y/SophisticatedStorage#506]
When using full 25x25 - 1 controller setup w/ ME hookup to the controller. The AE2 works just fine with no issues during gameplay. However if you leave and rejoin, sometime it’ll cause socket error crash with a whole list of all the barrels and no other mods mentioned 

playing on chroma endless 2

Had no issues when only using 15 barrels 
All barrels have double gold stack upgrade 
the barrels in photo were empty but still caused a crash. There is nothing else hooked up to the ME (basic ME with 4 preset subnets)

![Uploading 2024-10-11_21.10.50.png…]()
![2024-10-11_21 16 50](https://github.com/user-attachments/assets/ceed2bda-f4bd-4e23-8a50-b14c18f60f23)

**Comment by ChimeraGaming** [comment]
![2024-10-11_21 10 50](https://github.com/user-attachments/assets/b73535bd-f24e-4f48-83d9-22b05c9a62e8)
First image was struggling to upload.

**Comment by ChimeraGaming** [comment]
[crash-2024-10-12_23.59.27-client.txt](https://github.com/user-attachments/files/17353010/crash-2024-10-12_23.59.27-client.txt)
Another player crashed at my base and this is their crash log.

**Comment by P3pp3rF1y** [comment]
The only explanation I have for this is that you have invalid config in which number of upgrade slots is set to less than 0 because the code keeps going through the part where if this is less than 0 it takes the default config value and sets it on the barrel

**Comment by P3pp3rF1y** [comment]
If that is not the case I will need steps I can use to recreate because I have no other idea how this could be happening

**Comment by ChimeraGaming** [comment]
![image](https://github.com/user-attachments/assets/997620d8-17d0-4dbe-a42e-ddab14cde9fb)
![2024-10-13_07 22 22](https://github.com/user-attachments/assets/f52b33b8-88fc-4f63-bd2b-9dc29bad2d93)
![2024-10-13_07 22 50](https://github.com/user-attachments/assets/345cfa2f-ac4d-4c08-9577-498c8c350006)
![2024-10-13_07 23 09](https://github.com/user-attachments/assets/f295a855-db64-400f-8c3c-05e0f538d747)

Hope this helps?

**Comment by P3pp3rF1y** [comment]
Nope that doesn't help I still have no idea how to recreate. But I am now realizing the neighbor change is being called clientside which is unnecessary so even though I am not able to recreate the crash I can add a check that can prevent this code from being called and should stop your crashes.

**Comment by ChimeraGaming** [comment]
Recreate: 
5x5 chunk to bedrock (in case that causes issues)

3x3 ME system with 4 subnets (as shown in image) 

1 subnet with colorless smart dense cable leading to p2p tunnel linked to subnet 1 and red smart cable leading to storage controller w/ AE2 storage interface

sophisticated storage = 25x25 ( - 1 for controller) white netherite barrels with 2x gold stack upgrades each 

storage can be completely empty but still causes others (and myself) to crash.

crash happens upon joining world. I’ve only personally noticed it after being in the world, leaving for an extended time but the loaded Minecraft instance is still up, and then I try to rejoin world.  After closing the Minecraft instance and starting it back up - it works. 


thanks for doing what you can :)

**Comment by P3pp3rF1y** [comment]
the latest 1.18 release should solve this.

**Comment by ChimeraGaming** [comment]
Thanks!
