### ISSUE TITLE
[Forge 1.19.2 Feature Request] Port Sophisticated Backpack's noConnectionBlocks config feature to Sophisticated Storage

### ISSUE THREAD

**Issue by Geekerandy** [P3pp3rF1y/SophisticatedStorage#509]
In Forge 1.19.2's version of Sophisticated Backpacks, there is this config option to disallow connection with certain blocks. 
![image](https://github.com/user-attachments/assets/d2a536ff-01e1-443a-8c25-40cdaadbbca1)

However, in Sophisticated Storage version 1.19.2-0.9.7.765, this feature does not exist. Is it possible to port this feature over as well?
This is mainly due to a dupe issue with Refined Storage on their [end](https://github.com/P3pp3rF1y/SophisticatedStorage/issues/421), however it seems like the mod author does not support 1.19.2 anymore, as they did not backport their dupe fix to 1.19.2. 

That being said, I request to have the S.Backpacks connection blacklist feature be ported to Forge 1.19.2 S.Storage. I run a modpack on this version with the aforementioned mods, and I would ideally like to keep all of them in while also fixing the dupe issue. Because I've been doing it by accident.

**Comment by P3pp3rF1y** [comment]
Sorry, I don't maintain 1.19.2 with nothing but potentially critical bug fixes and this is definitely not one of them. Also adding a feature that doesn't have much regular use other than in cases where another mod doesn't want to fix their bug doesn't make much sense to me either, it's an unnecessary additional maintenance that would take away from other stuff.
