### ISSUE TITLE
Soph Storage Hopper Upgrade Voiding resources With Extended AE Extended inscriber ( interaction bug )

### ISSUE THREAD

**Issue by DreadFulEye** [P3pp3rF1y/SophisticatedStorage#511]
Basically the extended inscriber From " Extended AE " when crafted 2 stacks of Processors It produces LESS than a amount given

Tested
First Test:
Crafted stack of logic processing Which require

- 1 stacks of Redstone
- 1 stacks of printed silicon
- 1 stacks of printed logic circuit

With Soph Storage Hopper Upgrade Barrel ( First Video down below )

Answer
Made 44 Logic Processors with 20 redstone / 18 Printed Silicon 

2nd test
Crafted stack of logic processing Which require

- 1 stacks of Redstone
- 1stacks of printed silicon
- 1 stacks of printed logic circuit

With Hopper Insert

Answer
Made full stack of Logic Circuits

Video Proof
1.https://easyupload.io/b08jin

Links dont work, Please message me @dreadfuleye on discord <3

**Comment by P3pp3rF1y** [comment]
I am unable to recreate with just sophisticated storage + extended AE (plus all the require dependencies of course). So there's something in your modpack that's causing this issue or I am using more up to date versions that don't have the issue. Can't tell without any additional info. If you are able to figure out what mod is causing this i can take one more look if there's anything I would need to fix on my side, but looks like this will go to them.

**Comment by DreadFulEye** [comment]
> I am unable to recreate with just sophisticated storage + extended AE (plus all the require dependencies of course). So there's something in your modpack that's causing this issue or I am using more up to date versions that don't have the issue. Can't tell without any additional info. If you are able to figure out what mod is causing this i can take one more look if there's anything I would need to fix on my side, but looks like this will go to them.

Well the only modpack i used was a clean version with Ender io / Extended AE / Sophisticated storage 

The versions i was using were 
- EnderIO-1.20.1-6.2.1-beta-all ( just for powering it ) 
- ExtendedAE-1.20-1.1.14-forge 
- sophisticatedcore-1.20.1-0.6.34.718
- sophisticatedstorage-1.20.1-0.10.45.912

This can be recreated by just placing a soph storage on top of the extended AE inscriber change the setting to export and allow insert from all sides.. and have a Advance hopper upgrade inside the barrel with a hopper below it to catch the processors.

If you need more proof please message me on discord, and i will gladly live stream it for you or send u video proof of this bug.

**Comment by P3pp3rF1y** [comment]
Ok found the culprit - it's the creative power from EnderIO doing it. I wasn't able to recreate before because I was using Creative Energy Cell from AE to power the inscriber. The moment I switch to creative power from enderio the issue starts happening, when I switch back to AE creative one it's gone. So there's some really odd interaction between inscriber and enderio creative power or somehow the creative power gets inscriber into some invalid state where it starts eating up items if they are inserted faster than 1 at a time. Anyway you will need to report that to either ExtendedAE or EnderIO
