### ISSUE TITLE
some thoughts and questions

### ISSUE THREAD

**Issue by Sur1ngware** [P3pp3rF1y/SophisticatedStorage#512]
Hello, I really like your mods (including another backpack mod)!And I have a question:How should I use the Controller to put the items of a certain mod into the storage connected to the Controller?My idea is that after each adventure I put my Sophisticated Backpack on a controller connected to a hopper, and it will automatically store and sort it for me.

**Comment by P3pp3rF1y** [comment]
Please join our discord server and others can help you on there. Issues are just for that - logging issues with the mod, not having a conversation about it functionality.
