### ISSUE TITLE
World Corrupting Bug

### ISSUE THREAD

**Issue by Aoimina** [P3pp3rF1y/SophisticatedStorage#513]
If you copy the NBT of a chest that have magnet and you place it on the ground then place another one next to it that they become double chest it brick the entire world and the world become unusable til you remove sophisticated storage

Forge : 1.20.1
Sophsticated storage : 1.20.1-0.10.45.912

**Comment by P3pp3rF1y** [comment]
I assume you mean copy the chest in creative correct? Because I am not aware of a way to do it in survival

**Comment by P3pp3rF1y** [comment]
And actually I am unable to recreate because when I middle click a chest I get one without the upgrade so placing the chest will just work. so I will need more info on how to recreate or if you have modified config in some way. Also log would be useful in case it shows some error.

**Comment by Aoimina** [comment]
hold ctrl then middle mouse to copy something with its nbt data, and make sure the advanced magnet upgrade have filter in it ie an item in the filter also i remember its gold chest tier

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release, the already placed double chest is broken and you can use setblock command and set it to air, but any newly placed chests won't combine into double chest if they have upgrades in their nbt like this
