### ISSUE TITLE
[1.20.1] Incompatible with Apoli

### ISSUE THREAD

**Issue by DrSigma4164** [P3pp3rF1y/SophisticatedStorage#515]
I already wrote about it today, you asked to write about it in a separate issue.

- when a compression upgrade is installed in the barrel,
- the barrel is blocked,
- there is already at least one such item in the barrel
- you try to put items in this barrel, for example using a hopper, they are not inserted.
- at this moment, nothing is written to the logs
- Details in the video below
- This happens if there is still an Apoli mod installed: https://www.curseforge.com/minecraft/mc-mods/apoli-forge

Version:
minecraft: 1.20.1
forge: 47.3.1
sophisticated storage: 0.10.45.912
apoli: 2.9.0.8

https://imgur.com/a/QuU5h1r

**Comment by P3pp3rF1y** [comment]
Ok, so this one you will need to report to Apoli. They attach capabilities to stacks, but seem to do it in some strange way where the capabilities are not there when stacks are deserialized hence the gold ingot that passes through player's hand is actually different from the one in the barrel. I have no way of easily telling more about this as their code is closed source so it's up to them to figure out what they should be doing differently.

**Comment by DrSigma4164** [comment]
It seems that this mod has been discontinued for the forge version for 3 weeks. I understand that it is not your mod that is causing this bug, but could you please try to solve this problem on your end? If not, I'll think about removing Apoli from the modpack. Thank you in advance.

**Comment by P3pp3rF1y** [comment]
I can't solve it on my end without fixing their mod. I mean I could just ignore capabilities but then there could be other issues like items seemingly being converted from one to another if the only difference are capabilities. So the only way you can solve this in your pack is drop one of these mods
