### ISSUE TITLE
Sophisticated core not working on a server

### ISSUE THREAD

**Issue by Flying-Fire1** [P3pp3rF1y/SophisticatedStorage#519]
I have sophisticated core installed and up to date in the servers mod folder and when I launch my own Minecraft with the exact same mods installed it works, but the server crashes on startup.
https://cc.akliz.net/servers/383328/files/file?path=%2Fminecraft-forge%2Fcrash-reports%2Fcrash-2024-11-06_01.31.29-fml.txt
I've tried downgrading versions and no other versions work. When I remove sophisticated core it gives me a different crash report that actually looks like its caused by the absence of the mod but when I reinstall it it just gives me the old crash report again. 
The server runs fine without any sophisticated storage mods on it but I already have stuff stored in my backpacks on the server and this mod is by far my favorite storage and backpack mod.

**Comment by Flying-Fire1** [comment]
nvm I just had to copy specifically ATM9 version of sophisticated storage because I knew that worked and I dont even know man I hate this server host so much.

**Comment by P3pp3rF1y** [comment]
I don't have access to that log but based on your last message I am closing this now
