### ISSUE TITLE
The most recent version of sophisticated storage depends on a non-exsistent version of sophisticated core

### ISSUE THREAD

**Issue by YocyCraft** [P3pp3rF1y/SophisticatedStorage#524]
crash report: https://mclo.gs/FwdKbPO

The mod requires  0.6.49 or above, however such version doesn't exist on curseforge or modrinth.

**Comment by Ciellix** [comment]
I second this

seems someone beat me too this

**Comment by Ciellix** [comment]
version 0.6.49 was uploaded on curseforge(or at least it has shown up for me)

**Comment by P3pp3rF1y** [comment]
This was my bad not releasing the latest core that goes with the latest change in storage. It's now released so you can just update to it and issue is solved.
