### ISSUE TITLE
[All versions]: CTRL+Middle Click does not retain container contents if container size is non-vanilla

### ISSUE THREAD

**Issue by macbrayne** [P3pp3rF1y/SophisticatedStorage#530]
## Expected Behaviour:
1. Fill chest / barrel with items
2. CTRL+Middle Mouse Click (CTRL+"Pick Item") to add the container to the hotbar
3. Placing that chest from the hotbar retains chest/barrel contents

(See https://minecraft.wiki/w/Creative#Pick_block)

## Actual Behaviour:
The container will be empty.
It will work as expected with `sophisticatedstorage:chest`, `sophisticatedstorage:barrel` and `sophisticatedstorage:shulker_box`, it won't with any copper, iron, gold, diamond etc. chest/barrel/shulker box.

## Potential fix:
Override `public ItemStack getCloneItemStack(LevelReader levelReader, BlockPos pos, BlockState blockState)` in the affected blocks

## Versions affected:
Sophisticated Storage 0.8.46.624 using Sophisticated Core 0.5.98.458 on Forge 40.2.9 running on Minecraft 1.18.2
Sophisticated Storage 0.10.53 using Sophisticated Core 0.6.51 on NeoForge 21.1.77 running on Minecraft 1.21.1

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this, will need more info on how I can recreate because when I use ctrl middle click I get storage block which when placed has all of its contents.

**Comment by macbrayne** [comment]
Ok, I must have done something wrong yesterday while testing. It works fine actually...
