### ISSUE TITLE
Option for sme upgrades across both mods

### ISSUE THREAD

**Issue by zmarotrix** [P3pp3rF1y/SophisticatedStorage#532]
Not an issue but I could not find anywhere to put any suggestions. 

Please add a config that would allow the Backpack upgrades to work for either chests or backpacks and just remove chest upgrades. Or the other way around.

**Comment by P3pp3rF1y** [comment]
We have a discord server that is mentioned on the project page where you can discuss this stuff.

Anyway I am not going to make upgrades universally usable in both mods there are reasons they are separate like cost of upgrades and you have conversion recipes if you need to convert from one to the other.
