### ISSUE TITLE
Disabled recipe keeps getting enabled whenever I restart server.

### ISSUE THREAD

**Issue by zvn570** [P3pp3rF1y/SophisticatedStorage#533]
I've been trying to disable crafting upgrade on Storage and Backpack in the config, whenever I disable the recipe and restart the server, they become enabled again in config.

**Comment by P3pp3rF1y** [comment]
Anything in log about config reset? And are you changing it when the server is stopped?

**Comment by zvn570** [comment]
I changed it when server was running, does that cause config to reset when restarting?

**Comment by zvn570** [comment]
I changed the config when the server was offline, it's now working, thanks.
