### ISSUE TITLE
[1.21.1] Advanced Hoper Upgrade is not pulling through hopper pullable blocks or any other storage blocks.

### ISSUE THREAD

**Issue by ExiledMiner04** [P3pp3rF1y/SophisticatedStorage#534]
![image](https://github.com/user-attachments/assets/5d086dcd-5279-476a-9886-b8bbc7d2431f)
![image](https://github.com/user-attachments/assets/1f15ed24-8f7b-4482-8c18-2029e73a1811)

I had sugarcane falling on top of the mud from this "Leave it and forget" type auto farm and I came back to it still sitting on the mud blocks. Afaik mud allows items to be pulled through by hoppers.

I noticed this not working with anything else with storage in them like other mod blocks and even vanilla chests, etc.

**Comment by ExiledMiner04** [comment]
![image](https://github.com/user-attachments/assets/64345957-87c8-42e3-94fc-9e64e39d00f3)
These used to work in an older version with this mod as far back as 1.20.1 and before. I do know even silent gear is having trouble with even vanilla hoppers.

**Comment by ExiledMiner04** [comment]
I just tested with items on top of mud with vanilla hopper into a basic spruce barrel from your mod and it got pulled through.

**Comment by P3pp3rF1y** [comment]
hopper upgrades never had support for picking up item entities. You must have used magnet upgrades to pick these up or just plain vanilla hoppers. And it's not my intention to add support for item entities in hopper upgrades because other upgrades can pick these up so closing this.
