### ISSUE TITLE
1.18.2 Bug Report

### ISSUE THREAD

**Issue by NoNameGuest** [P3pp3rF1y/SophisticatedStorage#54]
Nice to meet you
Bug Report
Sorry for the machine translation
I get a crash when I open Chest&Barrel added in the mod.
Here is the crashReport URL

http://plsk.net/Minecraft_crash_MOD_report

**Comment by P3pp3rF1y** [comment]
Before posting here make sure that you have updated mods. Like in this case you have newer core than the one storage can support so just updated sophisticated storage to the latest and issue is fixed
