### ISSUE TITLE
Double chest Sophisticated Storage

### ISSUE THREAD

**Issue by IsseyFr** [P3pp3rF1y/SophisticatedStorage#540]
Hello, I have a small question, I added your mod in 1.19.2 for my survival, but I can not make double chest, but on the modpack steampunk which is in 1.20.1 it works is there an update that does this or is it a bug?

**Comment by P3pp3rF1y** [comment]
This feature was never added to 1.19.2 as that version was at that point pretty much just 1.20 prequel and didn't make sense to add in there. So you will need to play with newer versions to play with double chests.

**Comment by IsseyFr** [comment]
Thanks for the information, is there an addon that could make a double chest with your mod?

**Comment by P3pp3rF1y** [comment]
there isn't one and that would be super difficult for an addon to add anyway

**Comment by IsseyFr** [comment]
ok thx
