### ISSUE TITLE
[1.21.1] Search "breaking" the whole container, items move to top of screen

### ISSUE THREAD

**Issue by maxiboy211** [P3pp3rF1y/SophisticatedStorage#541]
Could be a SophisticatedCore issue but not sure, I can open one and link it if needed. Using the search bar in a chest or backpack moves all items out of the container to the top of the screen. All items are forced into a single row and stack on top of each other. They can still be interacted with. ~~If moved to player inventory while at the top, the correct chest slot they were in does become empty.~~ _Seems to be random how they stack and which "slot" works or not depending on the search._ Clearing the search returns them back to normal. Found this out while playing ATM10 v1.24.
EDIT: Only visible at certain GUI scales, visible on scale 2 and 1 on a 1080p monitor, out of screen on scale 3

Repeated on a clean instance using:
- MC 1.21.1
- NeoForge 21.1.80
- sophisticatedcore-1.21-0.7.12.793
- sophisticatedstorage-1.21-0.10.55.953
- Java - Eclipse Adoptium jre-21.0.5.11

(different instance on screenshots)
![2024-11-24_21 09 24](https://github.com/user-attachments/assets/0614571b-54bb-41e1-8a5a-968828b36cd4)
![2024-11-24_21 09 29](https://github.com/user-attachments/assets/bbc1f84b-ea06-47bd-8c31-3f117b12e278)

**Comment by P3pp3rF1y** [comment]
from those screenshots I don't see any issue at all. the search is supposed to work the same way it does in something like AE or RS where it only shows the slots that have the matched item. Or am I missing something here?

**Comment by maxiboy211** [comment]
Oh yea the search works great and I love the empty slots "disappearing" but if you look at the top middle of the second screenshots you can see the items aren't hidden but moved out of the container and stacked on each other. Diorite stairs and enchanting table textures clipping on the left and the wood and copper blocks right after, copper is hidden behind the wood and you can barely see the numbers are on top of each other, 19 and 6. Sorry if the first description didn't come across clear, kinda weird to describe I guess.

![2-2024-11-24_21 09 29](https://github.com/user-attachments/assets/5ec7142b-ca95-427d-b321-11448468691f)

**Comment by P3pp3rF1y** [comment]
Ahh right, sorry missed that. So yeah that reveals how this actually works - slots are not really removed, they are supposed to be moved out of the screen. Looks like I need to move them further away so that they couldn't be seen like this.

**Comment by P3pp3rF1y** [comment]
ok this is fixed in the latest release of sophisticatedcore on CF/Modrinth
