### ISSUE TITLE
Draconic Evolution Support

### ISSUE THREAD

**Issue by micmou** [P3pp3rF1y/SophisticatedStorage#543]
So im a storage density lover and I had a probably dangerous idea. Draconic Evolution Netherite Double Draconium chest.
<img width="1194" alt="javaw_fqtN61SKJb" src="https://github.com/user-attachments/assets/f7cc05fa-f5d2-4e3e-b0c8-331ffcb7d512">

Ive attached a image of the Single Draconium Chest

**Comment by P3pp3rF1y** [comment]
I am not going to pursue anything like that. Sophisticated stuff is really complicated as is and this would make it even worse. Like potentially in the future I could add a way to define chests made from dynamic materials with the defined number of slots, but I will see if that even happens. So I am closing this for the foreseeable future.
