### ISSUE TITLE
Storage access stuck

### ISSUE THREAD

**Issue by Spyro1502** [P3pp3rF1y/SophisticatedStorage#564]
## Forge Version : 
- 47.3.0

## [Sophisticated Storage](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage) Version :
- 1.20.1-1.11.3 

## [Simple Storage Network](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network) Version :
- 1.20.1-1.0.2.985 (with [Sophisticated Core](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core) 1.20.1-1.0.1.809)

There are other mods in the pack but I can't tell if some of them are implied, the system only use blocks from both mods

## Description : 
I used both [Sophisticated Storage](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage) and [Simple Storage Network](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network) for my base and did some correct wiring, but then the limited barrels seems to send wrong info as they frequently stop accepting items from my wires. The block is still detected but I can't add stuff anymore.

Here I made a video showing what happens : [https://youtu.be/x5KAteRz2eI](https://youtu.be/x5KAteRz2eI)

PS : The bug also happen if I add for exemple the 11 redstone then try to add any number after, it just seems to lock and I need to update the block for it to work again, but temporarily

Stable way I had here to have it happen here is to empty the barrel, then add some redstone again like in the video

**Comment by P3pp3rF1y** [comment]
I have seen this one before where people would have a mod that adds data to items which makes them different from seemingly same items. Are you actually able to recreate with just the two storage mods in the pack?

**Comment by Spyro1502** [comment]
Hmm Sadly it seems like I cannot, it only happens in the pack I made
Weird thing is that they can stack when added by other mean and are able to stack when I update the storage block itself, and it happens with any item
it definitely seems like there might be some kind of conflict, I wil try to look if I can find the mod causing it and will come back about it

**Comment by Spyro1502** [comment]
I just checked through a save editor and it didn't give me any clue yet sadly, also tested with refined storage to make sure the bug wasn't coming from simple storage and no, refined storage and even hopper can't push anymore either 
![image](https://github.com/user-attachments/assets/16204690-6c46-49d3-9674-eefff6b290d2)

**Comment by P3pp3rF1y** [comment]
So based on this it looks like the data may be in what in 1.20 was still "capability" data or it may be getting cleared from regular nbt and you just happen to look at the saved data with nbt already cleared. Anyway if you can figure out what mod addition will make this happen I can take a look at that more limited set of mods what's happening there (even though I am almost sure my response is going to be that you need to follow up with that other mod's owner on fixing how they attach the data). 

Just traced really quickly through discussions related to nbt on our discord and I can see this one mod that came up lately as attaching data:
`Fex's Vehicle and Transportation Mod`

**Comment by Spyro1502** [comment]
Okay, finding the source of the problem wasn't so easy, but it seems to come from the [Origin mod](https://www.curseforge.com/minecraft/mc-mods/origins-forge), I guess it was actually having effect on items in some ways ?

At least that's a mod we can add to the known incompatible mods I guess

Also I don't know if it may help doing a patch, probably not, but I looked at the data from blocks to compare one willing to accept the items and one that wouldn't, and here is the difference 
![image](https://github.com/user-attachments/assets/37d94513-9bc2-4b1b-8814-8819c52ae4e6)

Once I fixed the bug by removing Origin, `updateBlockRender: 1b` don't disappear anymore, maybe that's something to look into ?

**Comment by P3pp3rF1y** [comment]
Ahh that made me realize I saw origins in the past and there was an issue open for that some time ago #437. So yeah either they have to fix what they are doing with the data attached to stacks or you need to drop the mod for this to work. And `updateBlockRender` is just a flag that tells the block if it should send an update to client that udpates the render of the barrel so that's alright if it's missing sometimes and sometimes is present.
