### ISSUE TITLE
Sophisticated Llamas & Minecarts

### ISSUE THREAD

**Issue by Darinth** [P3pp3rF1y/SophisticatedStorage#565]
Like... I don't actually expect to see this... the Llamas in particular. But I have ran into a couple of instances where having the sophisticated treatment done to the minecart with chest would be handy. Llamas would be amusing at least.

**Comment by P3pp3rF1y** [comment]
You mean something like this? :D soon<sup>TM</sup>
![image](https://github.com/user-attachments/assets/ac7a279e-557d-4261-9c77-2f6da7c16667)

**Comment by Darinth** [comment]
You're my hero. ❤️

**Comment by P3pp3rF1y** [comment]
There is now https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage-in-motion so I am closing this and any suggestions can be tracked on that projects tracker

**Comment by Darinth** [comment]
There didn't even need to be a TM on that soon. You're awesome. :)
