### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by chinmay557** [P3pp3rF1y/SophisticatedStorage#568]
I accidentally found a dupe while playing atm9tosky i used a create mod sticky mechanical pistion to move the sophisticated storage chest(oak diamond chest) it was a double chest connected but when moved by the mechanical piston it separated  in 2 chests but their loot  didnt get separated  but got put in both of the chests

**Comment by P3pp3rF1y** [comment]
This is the same thing as #449 and requires either a different implementon or a compat layer on create side + compat on Sophisticated side as well. Closing this as I am already tracking the implementation in that issue
