### ISSUE TITLE
Crash before game loads after updating Sophisticated mods and Relics

### ISSUE THREAD

**Issue by MuteTiefling** [P3pp3rF1y/SophisticatedStorage#570]
We're trying to update sophisticated mods and Relics in Enigmatica 10. Currently the latest we're able to run is this:

![image](https://github.com/user-attachments/assets/793644a2-81db-4f20-9c1c-797db7b24b75)
![image](https://github.com/user-attachments/assets/2f4750f8-aa33-4cb3-a2c2-2ac34213e45f)

Updating beyond those results in a crash before getting to the world menu. 
https://mclo.gs/7BmdZjg
https://mclo.gs/yWovHA5

**Comment by P3pp3rF1y** [comment]
Looks like some mod is trying to inject into JukeboxUpgrade (maybe unintentionally) and their mixin fails `[31Dec2024 09:59:12.522] [modloading-worker-0/FATAL] [mixin/]: Mixin apply for mod disccord failed disccord.compat.mixins.json:JukeboxUpgradeItemMixin from mod disccord -> net.p3pp3rf1y.sophisticatedcore.upgrades.jukebox.JukeboxUpgradeItem$Wrapper: `

**Comment by MuteTiefling** [comment]
Ah, good catch. I've disabled DiscCord and that seems to resolve it. So, I'll just report over to them. Thanks for the assist!

**Comment by P3pp3rF1y** [comment]
alright closing this issue given that is the case
