### ISSUE TITLE
Feature Request: Paintbrush/Decorator Table "Reset" Option

### ISSUE THREAD

**Issue by frankrue** [P3pp3rF1y/SophisticatedStorage#571]
I found that after adding customizations to a barrel, I could not "reset" it to default state. It also meant I could no longer stack those barrels in my inventory, and other issues related to bulk updating/stacking/etc. From an aesthetics standpoint, I also could not get them to "match" other barrels anymore, there was also something a little off...

**Comment by P3pp3rF1y** [comment]
you can reset it using vanilla cauldron, the same way you would vanilla leather armor
