### ISSUE TITLE
Feature Request: Multiple magnet upgrades should increase the range.

### ISSUE THREAD

**Issue by SodiumShine** [P3pp3rF1y/SophisticatedStorage#58]
Multiple magnet upgrades should increase the range. Not necessarily by whole increments of what the base upgrade offers but _something_.

Of course, one could just change the config, but I think it's more fun and "balanced" this way.

**Comment by P3pp3rF1y** [comment]
I am not in favor of doing this - interaction between mods is one that introduces a lot of complexity and at the same time I feel the range of 11x11 on advanced is quite big one already.
