### ISSUE TITLE
Jukebox upgrade creates "ghost jukebox" when storage is mined/broken.

### ISSUE THREAD

**Issue by SodiumShine** [P3pp3rF1y/SophisticatedStorage#59]
To reproduce: Place a sophisticated chest or shulkerbox (I didn't test with the others) down, insert a jukebox upgrade, insert any disc and play it. While the jukebox upgrade is playing, break the storage. Music continues to emanate from the blockspace the storage used to be in. 

version 1.18.2-0.5.1.107
Forge 40.1.68

**Comment by P3pp3rF1y** [comment]
I will need more info on how to recreate this - any way I try to break it the music properly stops a fraction of the time after it is broken.

**Comment by SodiumShine** [comment]
Hm I don't really have more information unfortunately. I just mined it normally with a pickaxe, it was in single player. Might have been another mod interfering with it if you can't reproduce.

**Comment by P3pp3rF1y** [comment]
closing this one as I wasn't able to recreate and didn't have any additional reports on this with more info.
