### ISSUE TITLE
Settings are displayed over JEI, so im clicking JEI instead.

### ISSUE THREAD

**Issue by krjencik** [P3pp3rF1y/SophisticatedStorage#63]
![2022-08-21_08 18 05](https://user-images.githubusercontent.com/92643141/185778288-310d36c5-3a75-48a1-89ad-d71db86d317f.png)

**Comment by krjencik** [comment]
Minecraft 1.19.2

**Comment by P3pp3rF1y** [comment]
Fixed in the latest version on CF
