### ISSUE TITLE
JEI Compat error in `latest.log`

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/SophisticatedStorage#64]
I'm unsure whether this actually does any harm, but I thought I'd report it regardless 😄 

- sophisticatedstorage-1.19.2-0.5.1.106
- sophisticatedcore-1.19.2-0.5.1.97

https://gist.github.com/NielsPilgaard/af3ef9683d6979c1e00ceb3f6cd39e26

**Comment by P3pp3rF1y** [comment]
Fixed in the latest version on CF

**Comment by NielsPilgaard** [comment]
Thanks!
