### ISSUE TITLE
Item & fluid storage

### ISSUE THREAD

**Issue by Spyro1502** [P3pp3rF1y/SophisticatedStorage#74]
Hi ! 

Been looking about info for tanks as it was something not part of the mod yet and saw you plan adding that as separate block later according to this : https://github.com/P3pp3rF1y/SophisticatedStorage/issues/35

But I do think having that as an upgrade would be interesting, almost no mods have a single storage block for both fluids and and Items, and the backpacks require pump upgrade, which doesn't let us use the usual fluid pipes to move them

**Comment by P3pp3rF1y** [comment]
for storage I have no plans of putting item and fluid storage in the same block. My thoughts for staionary storage are that it should seprate blocks should server item / fluid / energy storage. I however have tanks on my list as you have said and you will be able to connect to them through the same controller that currently does only item handling. Closing this as I have the tank on the list of future enhancements already.
