### ISSUE TITLE
Gold Shulker Box delete item 

### ISSUE THREAD

**Issue by KirbyBrasse** [P3pp3rF1y/SophisticatedStorage#75]
Weird bug with a gold shulker box where items where voided when put in trough the inventory quit the save and reload the save. couldnt replicate it after some interaction with the gold shulker box. Case is : they are not 100% safe

**Comment by P3pp3rF1y** [comment]
I will need more details on this. They save their contents separately from the itemstack and only keep their reference to the storage in item's nbt. And the only way I can see this happening is if the itemstack's nbt was deleted by something. So it sounds like you have something in the pack that is happy about removing nbt from item?

**Comment by P3pp3rF1y** [comment]
any additional info you have here or should I just close?

**Comment by Drednite** [comment]
Sorry if this is a necro, but I was able to recreate this bug, (or at least a similar one) at first on accident. It seems like the shulker box doesn't stop you from inserting items from inventory when it is full, resulting in the items being lost.

To recreate:
Fill shulker box with any item (just putting one cobblestone into all the slots works)
Holding the shulker box or holding another item, right click as if to insert the item into the shulker box
The item will appear to be inserted as if into an empty box
The item is now lost

Replicated this bug with every tier of shulker boxes

**Comment by P3pp3rF1y** [comment]
@Drednite what versions of storage / core have you got?

**Comment by Drednite** [comment]
sophisticatedcore-1.19.2-0.5.68.306
sophisticatedstorage-1.19.2-0.8.26.443

**Comment by Drednite** [comment]
I'm using this modpack if this is just a weird interaction: Cottage Witch 1.19-1.14.9

**Comment by P3pp3rF1y** [comment]
I see that the pack has Quark. if `"Interpret Shulker Box Like Blocks"` setting is set to `true` in its config you will get that issue, but setting it to false fixes the issue. Could you just confirm that's what is happening for you?

**Comment by Drednite** [comment]
That seems to have been the issue, thanks for the help

**Comment by P3pp3rF1y** [comment]
closing this as it appears it was really Quark stashing overriding sophisticated one and saving the items into incorrect place where sophisticated doesn't save them.
