### ISSUE TITLE
[FEATURE REQUEST] Storage Link needs a tooltip

### ISSUE THREAD

**Issue by hron84** [P3pp3rF1y/SophisticatedStorage#76]
I trying to use Storage Link and - maybe I'm just not smart enough, but - I could not figure out how it works. Please add a JEI info / tooltip for the item how can I link it to a Controller, or how the block itself works. From visuals, it looks like a facade, but since the mod does not have cables I ran out of ideas how can I use the link.

I tried to use it in a use case when few rows of s.barrels has a single block airgap between and I guessed the link could work like a Storage Drawers trim, but after spending a hour with it, I am now unsure even in this.

**Comment by P3pp3rF1y** [comment]
Makes sense to me I will add a bit of tooltip to explain.

In the meantime: you place it on storage blocks that are not directly connected to the controller and then you can use the storage tool to link it to the controller which allows connecting storage block or multiple storage blocks to the controller remotely. for example a wall of barrels on the other side of the room can be fully connected by placing the link block on one of them and then linking it to the controller.

**Comment by P3pp3rF1y** [comment]
Added this tooltip as well as tooltips for a few other items
