### ISSUE TITLE
Storage Link will not store to the nearest container

### ISSUE THREAD

**Issue by Dr-WeiAL** [P3pp3rF1y/SophisticatedStorage#79]
When I use Storage Link with AE2, I found that sometimes the stored items are not containers attached to Storage Link, but other containers that are far away. This problem does not occur when using Storage Controller.
![image](https://user-images.githubusercontent.com/47446553/192107959-90c01801-fa38-441b-94a4-0766059ad7ed.png)
![image](https://user-images.githubusercontent.com/47446553/192107932-b42a0ce4-025e-4b3d-b835-1266899ea949.png)
When used in this way, sometimes it will not be stored in the nearest container first.

![image](https://user-images.githubusercontent.com/47446553/192108041-000f9291-0ff7-4df0-912f-65462ffd13ad.png)
When used in this way, it will be stored in the nearest container

**Comment by P3pp3rF1y** [comment]
I will need specifics on how exactly to recreate. By default the closest get attached first. 
debug tool (no recipe item so you need to give it to yourself) can help you with this - it shows order in which the storages are registered to controller

**Comment by Dr-WeiAL** [comment]
This seems to be fixed in the AE update a day ago?
I'll watch for another day and if the issue doesn't appear anymore I'll close this issues

**Comment by Dr-WeiAL** [comment]
It seems to be no problem. If it happens later, I will open it again.
