### ISSUE TITLE
Sophisticated storage / Framed blocks Crash when displayed on storage

### ISSUE THREAD

**Issue by GreenForzeGaming** [P3pp3rF1y/SophisticatedStorage#82]
HI! P3pp3rF1y so me and my wife has found a big bug that completely crashes the game and it is involving using the Framed blocks mod and displaying the blocks on the storages. it causes this crash where the player causes a double entety and tick lag where people near that chest crashes the game. and i beleve it has todo with the fact the blocks inserted into the block display has a double block feature. as off right now, all our hard work has been destroyed... and we wish that a fix could solve it.
[crash-2022-09-27_06.55.57-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/9654475/crash-2022-09-27_06.55.57-client.txt)
[crash-2022-09-27_07.01.15-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/9654477/crash-2022-09-27_07.01.15-client.txt)

**Comment by P3pp3rF1y** [comment]
As mentioned here the bug has been fixed in framed blocks https://github.com/XFactHD/FramedBlocks/issues/174 so closing this issue.
