### ISSUE TITLE
[1.18.2] Pickup Upgrade doesn't work.

### ISSUE THREAD

**Issue by StarskyXIII** [P3pp3rF1y/SophisticatedStorage#83]
Game Version: 1.18.2
Forge Version: 40.1.80
Mod Version: 
Sophisticated Core: 0.5.12.129
Sophisticated Storage: 0.5.17.152
Sophisticated Backpacks: 3.18.29.718

When I throw the item on the storages with Pickup Upgrade, it do nothing.
But backpack with Pickup Upgrade works well for me.

**Comment by DeadlyAccurate** [comment]
Same issue.

**Comment by lazydaizy** [comment]
this remains to be an issue in version 1.19.2-0.5.18.151

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
