### ISSUE TITLE
[Crash] After picking up create Machines with gobber tools

### ISSUE THREAD

**Issue by f0kx** [P3pp3rF1y/SophisticatedStorage#85]
https://pastebin.com/2V3jHskL

**Comment by P3pp3rF1y** [comment]
I don't really see how this crash is related to what you have described in the title, but I have this fixed in dev based on another bug report.

**Comment by f0kx** [comment]
when i break create machines with a gobber pickaxe or gobber paxelthe game will crash to desktop and after watching in the crashlog this was the output...i dont know if that has something to do with your mod..but i only can read sophisicated backpack in crashlog so i thought its because of this mod ... sry if that isnt the case

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
