### ISSUE TITLE
Rendering Crash When Reloading Assets

### ISSUE THREAD

**Issue by sme23** [P3pp3rF1y/SophisticatedStorage#86]
When a Sophisticated Storage chest is visible on-screen and F3+T is used to reload assets, the game crashes. In my testing, I've only used an Oak Iron Chest, but able to reproduce in an environment with only JEI + Sophisticated Storage. Using mod version 1.18.2-0.5.17.152.

[Crash Report](https://pastebin.com/AWSyFHLm)

**Comment by P3pp3rF1y** [comment]
fixed in latest release
