### ISSUE TITLE
Wrong textures

### ISSUE THREAD

**Issue by Sam9th** [P3pp3rF1y/SophisticatedStorage#90]
Switched out a Vanilla Tweaks texture pack, spruce barrels now look like this:

![2022-10-15_23 54 07](https://user-images.githubusercontent.com/17936463/196022782-21ddf1a6-679e-4db1-b204-888a1d0a4020.png)

Break particles are also wrong,,

![2022-10-16_00 07 34](https://user-images.githubusercontent.com/17936463/196023024-9f3cbaf6-5e44-4d02-8f05-0878ae0126ae.png)

**Comment by Sam9th** [comment]
fixed itself next time i got on the server

**Comment by P3pp3rF1y** [comment]
this is likely caused by cached models, I have added calls in code to invalidate cache any time textures refresh as that call was missing there (and is missing in the version that's live at the moment)
