### ISSUE TITLE
Crash when entity loaded

### ISSUE THREAD

**Issue by Lennox186** [P3pp3rF1y/SophisticatedStorage#92]
used the item display option on a golden barrel that I put on my world, and right after confirming the config, game just crashed and whenever I tried to load it, just crash again.

I was running this world on server and realised that the server still running, after that I tried to load the world on SP, but it crashes either way

The barrel iteself had the stack itens upgrade and auto blasting upgrade

After removing the mod from the server, it prompted "ignoring entity sophisticatedstorage" and loaded normaly just without any barrel or chest that was upgraded (pretty obviously) and neither had any block on the location, with that it was possible to enter the world without crashing and get the exact coord where the barrel were, is that possible to reset this display option that I activated on server prompt?

**Comment by Lennox186** [comment]
This is the crash that o got from my

[crash-2022-10-29_14.29.55-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/9894328/crash-2022-10-29_14.29.55-client.txt)

**Comment by P3pp3rF1y** [comment]
That looks to me like optifine messing with rendering code - that method that the exception complains about not being there clearly exists in forge so something is removing it and optifine is very likely cause especially given that I found a similar crash for another mod where optifine was the cause. So try removing that and let me know

**Comment by Lennox186** [comment]
It worked! thanks for the help. Only thing it's that I lost all the itens inside the chest, probably 'cause I loaded the game without the mod!

Even though thanks for the help! great project! keep it up!
