### ISSUE TITLE
Does not display the correct name for named chests

### ISSUE THREAD

**Issue by brianfreud** [P3pp3rF1y/SophisticatedStorage#93]
If I name a colored chest on an anvil, the name displays correctly in the backpack, but reverts to "Chest" when the chest is placed in the world.  Using v1.18.2 with forge

**Comment by brianfreud** [comment]
Sorry, I'm referring to the name displayed with WTHIT; there may be some internal name not getting set for WTHIT to use, as it normally does correctly the names of named items such as vanilla chests.

**Comment by P3pp3rF1y** [comment]
fixed in latest release
